### ISSUE TITLE
Default calendar preventing other calendars from displaying.

### ISSUE THREAD

**Issue by chadcurry** [marcoancona/MineTime#1]
Thank you for your work on this. I'm running Ubuntu (most likely doesn't matter I know since this is Electron). I have a weird issue where my Google calendar, which is my main calendar is not showing up and will remove other calendars from view. If I deselect it from display, it will show all the other calendars on my calendar. I've tried removing all calendars but mine, and no joy. I've removed the account and relinked, but it did not work. I reset data and still no good.

**Comment by marcoancona** [comment]
Thanks. This will be fixed in the next release, expected next Wednesday.

**Comment by marcoancona** [comment]
This is fixed is 1.0.3. Let me know if the problem persists.

**Comment by chadcurry** [comment]
I'll download and check it out today. Thx!!

On Wed, Apr 19, 2017 at 8:45 AM, Marco Ancona <notifications@github.com> wrote:
Closed #1 [https://github.com/marcoancona/MineTime/issues/1] .
