### ISSUE TITLE
Add contacts to MineTime

### ISSUE THREAD

**Issue by mribeirodantas** [marcoancona/MineTime#100]
Some of my contacts were somehow imported to MineTime, however they are not the same ones I have in my Google account. Some are not even in the Google account and I do not know where MineTime took it from. I have recently added some contacts to my Google Account (Contacts) that I would like to add to my agenda with MineTime but it's not clear know how to do it.

**Comment by marcoancona** [comment]
MineTime currently does not support contacts. What you see in MineTime are "attendees" of events in your calendar.

**Comment by marcoancona** [comment]
I'll close this as a duplicate on #37
