### ISSUE TITLE
How to get public holidays into MineTime?

### ISSUE THREAD

**Issue by andreas-h** [marcoancona/MineTime#102]
It would be nice to have public holidays in MineTime. Many providers offer iCal subscriptions for this.  I tried adding the URL https://www.schulferien.org/deutschland/ical/download/?lrid=32&j=2019&t=2 under "Subscriptions", but get the error message "Calendar feed cannot be parsed".  The logs on the console don't show anything.

**Comment by marcoancona** [comment]
It seems the link you used does not point directly to an ics file. If I follow the link I end up on a page where multiple calendars are listed. You can select one of those calendars and enter the captcha to obtain the direct link to the ics feed.

**Comment by andreas-h** [comment]
Wow, that's embarrassing.  I hadn't actually clicked on the link but just blindly copied it.  Of course, everything works now.  Thanks so much, Marco, and please accept my apologies for acting so stupidly.
