### ISSUE TITLE
Specify license?

### ISSUE THREAD

**Issue by dtzWill** [marcoancona/MineTime#103]
I'm packaging this for NixOS, and was wondering if there was a clear answer for "what license is this released under"?

The README says:

> MineTime is totally free but not open-source (yet)

Which is great (truly ^_^) but from packaging point-of-view a lack of a clear license (preferably a recognized one, having an SPDX identifier) means this is at best 'unfree' and IANAL so I'll stop there.

Anyway thanks for this application and your work, LMK about the license please when you get a chance.

Thanks!

**Comment by marcoancona** [comment]
In this context, free means "can be used at no cost". The license is proprietary.

**Comment by dtzWill** [comment]
Okay, thank you for the quick response.  Enjoy the rest of your day!
