### ISSUE TITLE
Some more keyboard shortcuts

### ISSUE THREAD

**Issue by 5472qaywsx** [marcoancona/MineTime#105]
Hi, and thank you for your fantastic software.
My "issue" (actually an enhancement request) is related to "issues" #12, #26, #40 and #78.
I'm an almost mouse-free user of software, and therefore ask you what do you think about adding following keyboard shortcuts:
- to (toggle) focus on the "Type here" field;
- to insert a new event (open the "New event" dialog);
- to toggle "day/agenda/week/month" view;
- to open the "analisys" window;
- to open the "manage calendars" window;
- to toggle the "assistant/calendar/attendees" dialog.

Keep up the good work!
And remember, as soon you open the code, that there is a whole community willing to help!
Cheers,
Dan

**Comment by marcoancona** [comment]
New in version 1.5.0
- Ctrl/Cmd+Space: toggle assistant "Type here" field
- Ctrl/Cmd+F: search in calendar
- Ctrl/Cmd+D: duplicate and event

**Comment by 5472qaywsx** [comment]
This is awesome! Tanks dude! Grazie 1000!

**Comment by 5472qaywsx** [comment]
Hi again,
just wanted to point out that I created a github "repository" where I collected all keyboard shortcuts of your program: search for "minetime-kbd-shortcuts", and feel free to pick it up and integrate in your project.
Cheers,
Dan

**Comment by ahmedelq** [comment]
Hi Marco, would love to see a shortcut to display a list of shortcuts :) e.g `Ctrl + / `

**Comment by 5472qaywsx** [comment]
Closing, as the software will disappear from github, see #254 .
