### ISSUE TITLE
Not working on OpenSuse 15.0

### ISSUE THREAD

**Issue by lucianopasi** [marcoancona/MineTime#107]
Hi and thank you for your work on Minetime.
I tried to install it on OpenSuse, different versions, mainly on 15.0, KDE 4
The first problem is the request for libappindicator: no such library. Through YAST I found and installed libappindicator 1 and libappindicator 3-1 instead
Secondly, the app starts, it gets the right calendars on my Google account, but it can't apparently download them: the round icons to the left of each calendar in the Calendars view keep rotating without end. In a similar way, any new event added to the agenda is not saved.
Any hint on how to solve the problem and get a workable application?
Many thanks

**Comment by marcoancona** [comment]
Might this be related to #98?

**Comment by lucianopasi** [comment]
I thought so. But libsecret-1-0, libsecret-devel and libsecret-lang are installed. I just added git-credential-libsecret. to no avail. the wheels are still spinning! Thanks

**Comment by marcoancona** [comment]
Did you also have `gnome-keyring` and `seahorse`?

**Comment by lucianopasi** [comment]
Should I? I have KDE, I thought gnome related libraries would not be needed. But I did install them right now and at least the calendar is linked now. 
I have an issue with attendees now, but this is another matter, thank you

**Comment by marcoancona** [comment]
Yes, `libsecret` is not enough if there is no secret service running. I will close this.
