### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by setegonz** [marcoancona/MineTime#11]
I'm on macOS 10.12.6. MineTime was working perfectly until today that hundreds (literally hundreds) of notifications start to appear and then the app crash.

**Comment by marcoancona** [comment]
By notifications, do you mean upcoming events notifications?


Il giorno 5 ott 2017, alle ore 08:09, setegonz <notifications@github.com<mailto:notifications@github.com>> ha scritto:


I'm on macOS 10.12.6. MineTime was working perfectly until today that hundreds (literally hundreds) of notifications start to appear and then the app crash.

**Comment by marcoancona** [comment]
Fixed in 1.0.12
