### ISSUE TITLE
Need to verify email even if using only local features

### ISSUE THREAD

**Issue by wcerfgba** [marcoancona/MineTime#111]
If users are disabling personalization I do not think they should need to verify their email.

Screenshot: https://postimg.cc/YLMpj9xt

This is particularly frustrating because this blocking interaction happens _after_ I've already connected my calendar.

**Comment by marcoancona** [comment]
Unfortunately, at the moment the email verification is a required step. This happens after connecting the calendar just because the email is automatically inferred from the calendar in most cases.
