### ISSUE TITLE
Cannot create events

### ISSUE THREAD

**Issue by wcerfgba** [marcoancona/MineTime#112]
I have no idea how to create an event. There is no button for 'Add event anywhere'. I tried using the assistant but for anything of the form "<do something> tomorrow" it just says it's confused. :(

**Comment by marcoancona** [comment]
Thanks for the feedback.
If you know when you want to schedule the event you can simply click and drag on the calendar view as other calendar apps.
If you wish to use the assistant you can try “Event tomorrow”, “Call tomorrow”, “Schedule new meeting” or similar. I am afraid “tomorrow” alone does not mean much.


On 16 Apr 2019, at 18:52, John Preston <notifications@github.com<mailto:notifications@github.com>> wrote:


I have no idea how to create an event. There is no button for 'Add event anywhere'. I tried using the assistant but for anything of the form " tomorrow" it just says it's confused. :(

**Comment by wcerfgba** [comment]
Thanks, I've managed to add an event by clicking on the grid in week view.
