### ISSUE TITLE
Insights window doesnt always resize correctly

### ISSUE THREAD

**Issue by FattusMannus** [marcoancona/MineTime#113]
If you have the main app windowed, open the insights dialog, then maximize the main window, the insights window doesnt alway resize correctly.

Reproducable on MacOS Mojave

**Comment by FattusMannus** [comment]
<img width="1680" alt="Screenshot 2019-04-21 at 08 25 07" src="https://user-images.githubusercontent.com/724328/56466875-7b740980-640f-11e9-8018-7f834bc34e0c.png">

**Comment by marcoancona** [comment]
This should be fixed now. If the problem persists feel free to leave a comment here.
