### ISSUE TITLE
Add possibility to disable clipboard monitoring (or remove it at all)

### ISSUE THREAD

**Issue by fbartels** [marcoancona/MineTime#116]
Hi,

I just installed MineTime because it popped up in my timeline and I wanted to give it a quick try. A first turn off was seeing a Github link, but then no source code (but you are already discussing this in #3). After installing one needs to enter his email address and then receives the following email with an activation code:

![image](https://user-images.githubusercontent.com/1257835/56562729-57006480-65aa-11e9-8645-2113f93ccab4.png)

What concerns me here is that MimeTime (at least until the point in time when you enter the activation code) needs to continuously monitor the clipboard of ones os for this to work, potentially also seeing other items that are put in there (don't people love to copy & paste passwords?).

- What is the purpose of this monitoring? (apart from catching the activation code)
- can it be disabled?
- will MimeTime listen to the clipboard even after activation?

**Comment by marcoancona** [comment]
I see your point. Here are some clarifications.

- At the moment, clipboard monitoring is only used for the activation. In the future, we would like to detect event information from it (eg. imagine you just copy a sentence indicating place and time of an upcoming event from your email and MineTime suggests the creation of the event in your calendar accordingly). This is a feature that the user will be able to turn off.

- the clipboard listener if only active when a new activation code is sent. If you restart the app after the activation, it will not listen for the code.

- the listener works by matching the regex `/^mt-[1234567890abcdef]{20}$/gm` to the clipboard content. Anything else is just ignored.

This is only meant to make the registration process smoother. 

Just let me add a broader personal opinion: while I understand the privacy concerns, I would like to point out that any application could listen to the user clipboard without informing the user. Moreover, when you install an application in your system, you are implicitly granting a lot of trust to such an application, which has full access to the file system. With MineTime, for example, users *enter the password* of their calendar accounts, for those providers that do not offer OAUth. We can assure that the password is never transferred to our servers but some level of trust will be necessary. The clipboard concern seems minor to me if we look at what an application could, potentially, have access to. Happy to hear any comments to this.

**Comment by fbartels** [comment]
> any application could listen to the user clipboard without informing the user

yes, that is if course also true. On Android/iOS app need to request specific permissions, but something like that has not reached the desktop os area.

But as you also said in the end it comes down to trust, and trust is in most cases not simply given but earned. One way to earn the trust for monitoring the clipboard would be an additional notification that MineTime will listen to the clipboard in the background to make it easier to the user to activate it.

But I am generally already relieved to learn that it only listens until it has received the activation code.

**Comment by marcoancona** [comment]
Clipboard monitoring for the activation code was eventually removed in 1.8.4. Now the activation code needs to be manually copy-pasted. Closing the issue.
