### ISSUE TITLE
Ability to open other office365 calendars

### ISSUE THREAD

**Issue by radaczynski** [marcoancona/MineTime#118]
I have a feature request for you :).

Currently for my work office365 account I can open my own calendar and a bunch of generic company calendars (holidays in various countries). There is an option to add another account but I need to have delegate access.

In office calendar there is an option to see other people's calendars without delegate access. The visibility depends on the access level (for some people you can only see the free/busy/tentative/away for some you can see full details of each meeting). This is a really useful feature in a corporate environment and I would like to see that in minetime as well.

**Comment by marcoancona** [comment]
MineTime already supports access to delegate calendars. Please try with the "Add delegate" button, which can be found on the lower part of the account settings view. On some accounts, this would only give access to calendars of people who have shared their event info (not only free/busy access). 
![image](https://user-images.githubusercontent.com/2278117/58318810-d3d86580-7e18-11e9-8f64-b4e7233b9c5e.png)

**Comment by radaczynski** [comment]
Indeed, I assumed that this was only possible for calendars that you had delegation for. THanks for clarification!

**Comment by radaczynski** [comment]
and you are right, in my case I can only add calendars, where I can view details of the meetings. I cannot add calendars of people for whom I can only see free/busy.

**Comment by radaczynski** [comment]
@marcoancona : is there an option to see calendars where you do not have the full access to? If not, is that something you can consider for your backlog?

**Comment by radaczynski** [comment]
@marcoancona : do you know what are the deciding factors in being able to add calendars wiht only free/busy/away/tentative access and not full details?

**Comment by radaczynski** [comment]
one other question: could minetime distinguish visually between tentative, free, busy and away? currently all of them are displayed exactly the same.
