### ISSUE TITLE
Shared CalDav doesn't work

### ISSUE THREAD

**Issue by LoosGuccreen** [marcoancona/MineTime#119]
Hello

Your app is great! So far I love it.

I've encountered an issue though: shared calendar doesn't work through CalDav (only the local calendar sync).

Could it be possible to fix this issue?

Thanks! I'm available if you need debug infos (but I don't know how to get them from the app).

**Comment by RicoLaaa** [comment]
+1 can see only my main calendar, MineTime is of no use to me if it doesn't display the shared calendars.

**Comment by Yalda666** [comment]
Same thing here, thanks a bunch in advance for your great work! :)

**Comment by marcoancona** [comment]
Just to clarify, MineTime does not import delegates calendars automatically. You can do so by using the "Add delegate" button. Do you have issues with this?

![image](https://user-images.githubusercontent.com/2278117/58319000-3a5d8380-7e19-11e9-83d7-e6907b200eba.png)

**Comment by RicoLaaa** [comment]
@marcoancona thanks for pointing this out, I indeed missed the + (maybe some UX work to do on this).
Is there a way to have the delegates to be automatically added (like on apple calendar?). I have like 20 delegate calentars and don't fell like having to look and copy/paste each URL manually.

PS: in apple calendar they even show the shared calendar without having to go to the delegate tab to add them.

cheers

**Comment by LoosGuccreen** [comment]
Indeed, I've missed the plus button. So it's not a missing feature by itself, more like an UX issue, as said by @RicoLaaa

**Comment by marcoancona** [comment]
I will close this, as the problem seems solved. In the last update, we have also made the button more visible.
