### ISSUE TITLE
FR: Please consider adding keyboard shortcuts

### ISSUE THREAD

**Issue by mdmayfield** [marcoancona/MineTime#12]
Many users find it quickest to interact with applications using the keyboard. Unless I'm missing something, MineTime 1.0.10 doesn't appear to offer any keyboard shortcuts. It would be nice to have some essentials like:

- Page Up / Page Down to move to previous/next day/week/month
- Ctrl/Command - T to go to Today

**Comment by marcoancona** [comment]
New in 1.2.0: Keyboard shortcuts
- Page Up / Page Down to move to previous/next day/week/month
- Ctrl/Cmd - T to go to Today
- Ctrl/Cmd - N new event
- Ctrl/Cmd - W toggle window (this is a global shortcut, must be enabled in app settings)
