### ISSUE TITLE
Synology WebDAV/CalDAV Server - Authentication Failed

### ISSUE THREAD

**Issue by itman2000my** [marcoancona/MineTime#125]
Hi.

Synology DS916+
Firmware: DSM 6.2.1-23824 Update 6
WebDAV Server: 
   1. Enabled HTTPS
   2. Enabled Anonymous WebDAV
   3. Enabled CalDAV

MimeTime 1.5.1 running on Windows 10 Version 10.0.17134.829

URL: https://XXXXXX:XXXXX/CALENDARS/Church_Events/

1. Use actual user name and password - FAIL
2. User anonymous user and password - FAIL

Other Apps like ThunderBird EMail/Calendar, DAVx5 (Android) & iOS native Calendar are working fine using both "anonymous" user and actual user ID & password.

Attached screenshot of the error.

![2019-06-21_12-22](https://user-images.githubusercontent.com/3981148/59897471-658ac100-941f-11e9-88d1-877c5b9abd3e.png)

Thanks for the help.

**Comment by esonn** [comment]
I can confirm this issue. I do not use Nextcloud but a stand-alone Radicale instance on Linux; Minetime 1.5.1 also runs on Linux.

Problem: My primary account, linked many months ago, appeared to be working as normal. However, *new* events only appeared when issued through Minetime itself. New events created from e.g. iOS Calendar do not appear in Minetime (but the other way round, they do).

There is no error dialog unless trying to relink an existing calendar or link a new one. My credentials work for sure, have cross-checked with other clients. This seems to be a kind of catastrophe... I have also checked the linking/relinking process with 1.5.0 and 1.4.12, neither of them worked as expected.

**Comment by tiernap** [comment]
i also experienced this problem. the solved it by moving away from the "webdav" application on synology for calendars and instead use the "Calendar" application. (https://www.davx5.com/tested-with/synology)

**Comment by marcoancona** [comment]
We have recently implemented a fix for Synology. This should solve the issue. Fee free to comment if the problem persists.
