### ISSUE TITLE
Moved event's length changed to 1 hour

### ISSUE THREAD

**Issue by mocsa** [marcoancona/MineTime#127]
I have a 2 hours long event in my caledar which I want to move to a different date. I have the following problem:

- I double click the event in my calendar.
- I click the date, so a popup opens where I can change the start and end date.
- I pick a different start date. End date is irrelevant, because the event does not span multiple days.
- The event is moved to the new date.
- The event start-time remains unchanged, but the **end-time is changed automatically** so that the **event length becomes 1 hour**.
- This is very frustrating, because now I have to restore the original length. For this I have to memorise the length before I change the date.

This happens with every event which has a length different from 1 hour.
I would be happy to use drag-and-drop as an alternative, because it does not alter event length. But I cannot drag events from the current week to the next week. In that case I'm forced to use the above (frustrating) technique.
I use version 1.5.1

**Comment by marcoancona** [comment]
Thanks for pointing out. Will be fixed in the next release.

**Comment by marcoancona** [comment]
Fixed in 1.6.1
