### ISSUE TITLE
Arrow keys navigate two weeks at a time

### ISSUE THREAD

**Issue by seschi98** [marcoancona/MineTime#128]
When you press the arrow keys in week mode, it always skips one week. For example it goes from week 32 directly to 34. If you use the buttons on the top right corner, the navigation works correctly.

I am using the latest version (1.5.1) on Linux.

**Comment by marcoancona** [comment]
I can't reproduce the problem. What version of Linux are you using?

**Comment by seschi98** [comment]
I am using a distribution called Deepin (15.11) which is based on Debian

**Comment by marcoancona** [comment]
Could you please check if the problem persists with 1.6.1?

**Comment by seschi98** [comment]
Just updated to the latest version and it is working properly now. Thanks a lot!
