### ISSUE TITLE
Dark Theme Variant? 

### ISSUE THREAD

**Issue by dishcandanty** [marcoancona/MineTime#13]
No real details needed here. Calendar looks great, but imagine if it had a dark theme :dancer:

**Comment by phwelo** [comment]
would be similarly great if the css was exposed somewhere, and could be touted as a feature expansion

**Comment by marcoancona** [comment]
This is in our backlog, but some other features have priority at the moment.

**Comment by marcoancona** [comment]
Long-awaited,  the Dark Theme is finally available in 1.3.0. I will close this.
