### ISSUE TITLE
Support for zoomable interface

### ISSUE THREAD

**Issue by Arty2** [marcoancona/MineTime#130]
Currently the interface appears too large in HighDPI displays in Windows, therefore combined with a small screen size, it's impossible to fit a day (at least the waking hours) in a vertical view.
Ideally it would be zoomable, which is pretty standard in many Electron apps.

**Comment by marcoancona** [comment]
Could you please post a screenshot of how it looks on your screen?

**Comment by Arty2** [comment]
![image](https://user-images.githubusercontent.com/3519269/63977628-f2579800-cabc-11e9-9b69-cce44f31cc30.png)

Kudos on the excellent work on the user interface by the way, it's extraordinary given the constrains the scope this project seems to have.

**Comment by Arty2** [comment]
@marcoancona Any plans for this one? I would be a great leap towards making the app usable for me on a laptop.

**Comment by marcoancona** [comment]
Just released 1.7.3 with support for zoomable interfaced. Let me know if this helps with your use case.

**Comment by Arty2** [comment]
Indeed it does, it fits smaller windows. Much appreciated!
What would be ideal, if there was also some resolution awareness, so that
switching between screens allowed different zooms.
