### ISSUE TITLE
Plain quotes ( " ) are not properly escaped

### ISSUE THREAD

**Issue by Arty2** [marcoancona/MineTime#133]
Quoted calendar events, eg. `"Event Name"` display the escape character: `\"Event Name\"`

**Comment by marcoancona** [comment]
Does this refer to the event title or the event body/notes? A specific calendar provider (Google, Exchange, etc)?

**Comment by Arty2** [comment]
I've had it happen on the event title, in linked (not certain of the term) calendars, that is calendars that synchonize from an .ical URL.

**Comment by marcoancona** [comment]
Cannot reproduce this issue. Does the problem persist with the latest MineTime version (1.7+)?

**Comment by Arty2** [comment]
Seems to not occur anymore. Appreciate the follow up.
