### ISSUE TITLE
Request: recurring events until a point in time

### ISSUE THREAD

**Issue by Altai-man** [marcoancona/MineTime#134]
Having recurring schemes like "Every day until 12th" or "Every other day this month" will help a lot, as right now an event added like "every other day" has to be removed if it is outdated due to circumstances change (e.g. university classes changes, etc), which removes part of the history.

**Comment by marcoancona** [comment]
You can already do this. Please try `Every day until 12 september`

**Comment by Altai-man** [comment]
Indeed. I wonder what was wrong... Sorry for the time taken.
