### ISSUE TITLE
MineTime Month view doesn't update highlighted "Today"

### ISSUE THREAD

**Issue by mdmayfield** [marcoancona/MineTime#14]
Steps to reproduce:

1. Open MineTime (let's say today's date is October 10)
   - Note that in Month view, the current date (for example October 10) is correctly highlighted in blue
2. Leave the MineTime window open all day, optionally minimized, *without changing from Month view*
3. On October 11, observe the MineTime window, still in Month view
   - Bug: Note that October 10 (yesterday) remains highlighted
   - Expected behavior: October 11 (today) is now highlighted and October 10 is not

Workaround:
   - Each day, when first looking at the calendar, switch it away from Month view and back

This issue is observed on an Ubuntu 16.04 LTS system running the Unity 7 desktop. I have not tested on other OSes or desktop environments.

**Comment by marcoancona** [comment]
Confirmed bug with all OSes. Will fix in the next release.

**Comment by johnhainline** [comment]
This actually occurs in Week view as well. The highlighted day stays the same if the program remains open without any screen changes.

**Comment by marcoancona** [comment]
Fixed in 1.4.0
