### ISSUE TITLE
Cannot access Outlook/Exchange/Office360

### ISSUE THREAD

**Issue by fakkoweb** [marcoancona/MineTime#141]
Even though I have proper credentials, I get this whenever I try to access.

![image](https://user-images.githubusercontent.com/4292783/64491825-f463e880-d26c-11e9-986c-1d36f6eeb13e.png)

Other online services redirect me on the outlook page to accept the authorization, just like this app does with Google.

At the current time I cannot use it because outlook does not work.

**Comment by marcoancona** [comment]
We do not experience any issue with out test accounts. Some more information might be useful to identiy the problem:
- is your email an `outlook.com` email?
- is the login mail the same you see if you log into `https://outlook.live.com` and click on your profile?
- do you have two-factor authentication enabled?

**Comment by marcoancona** [comment]
MineTime 1.6.3 comes with a new Autodiscover service. This should be solved now. Feel free to reply if the problem persists.
