### ISSUE TITLE
Cannot connect on CalDAV : UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by jeey** [marcoancona/MineTime#149]
I can't connect on my CalDAV server : 
Authentification failed. Please check your credentials and the server adress. You might use the CalDAV "Principal URL" as server adress.

I checked my credentials and tried as many "Principal URL" I can.

In the console, I've got this message :   

`warn: CalDAV account creation failed with message=unable to verify the first certificate, stack=Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1257:34)
    at TLSSocket.emit (events.js:194:13)
    at TLSSocket._finishInit (_tls_wrap.js:734:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:566:12), code=UNABLE_TO_VERIFY_LEAF_SIGNATURE
`
MineTime 1.6.2
Linux Mint 19.2 Tina
CalDAV server on Synology NAS

**Comment by marcoancona** [comment]
There seems to be an issue with the certificate chain provided by your CalDAV server? Is self-hosted or is a third party service that we can test?

**Comment by jeey** [comment]
it's self-hosted, not easy to test on your own. I try to take some 
informations you can use.

Le 30/09/2019 à 09:56, Marco Ancona a écrit :

**Comment by marcoancona** [comment]
This should be fixed with 1.7+ (MineTime asks whether to create an exception for connections that do not appear secure). Feel free to comment here if the problem persists.
