### ISSUE TITLE
Cannot add notes on new events

### ISSUE THREAD

**Issue by oserban** [marcoancona/MineTime#15]
Ubuntu 16.04

I cannot add notes on newly created events. I type and nothing happens and when I leave the field, the last char typed appears.

**Comment by mdmayfield** [comment]
I am seeing this as well, on Ubuntu 16.04, adding or changing notes on any event. This issue does not occur in the Location field.

One (awkward) workaround I have used is:

1) Enter text elsewhere
2) Copy
3) Click on event's Location field
4) Paste (nothing will be visible)
5) Press Tab (pasted text will appear)

**Comment by marcoancona** [comment]
Confirmed. Will be fixed in the next release.

**Comment by marcoancona** [comment]
Fixed in 1.0.12
