### ISSUE TITLE
Improvement: Automatic update on Windows 10

### ISSUE THREAD

**Issue by pablorq** [marcoancona/MineTime#153]
Hi,

To apply the v1.6.3 update I have had to download the installer .exe file and run it as installing a new software, which could be complicated on Windows 10 because of admin rights.

Can you, please, add a way to update the app without having to 'reinstall' it?

Thank you in advance!

Regards.

**Comment by marcoancona** [comment]
Do you mean that the auto update did not work? Did you see the update button appearing on the bottom right side of the screen?

**Comment by pablorq** [comment]
I'm afraid not. No update button.

:(

**Comment by marcoancona** [comment]
It might take a few hours and a restart of the app for this button to appear. You probably learned about the new release before MineTime could notify you.

**Comment by marcoancona** [comment]
How did you learn about the update, by the way?

**Comment by pablorq** [comment]
Maybe was that.

I though I learn it from you:

![imagen](https://user-images.githubusercontent.com/774839/67011509-0ea4a800-f0f0-11e9-8ec8-7aa1138bc6da.png)

**Comment by marcoancona** [comment]
I will close this, as the auto-update is already available.
