### ISSUE TITLE
Document options

### ISSUE THREAD

**Issue by Iambecomeroot** [marcoancona/MineTime#155]
I came here looking for the `--hidden` option. This was already added thanks to #117, but I had no way to find the option other than the issues.

It would be nice to have a list of available options with `--help` or a manpage. Currently, `--help` just launches MineTime, which is rather counter intuitive.

**Comment by marcoancona** [comment]
There are no other options expect `--hidden` so we have no documentation for this. Since MineTime is not supposed to be a CLI tool, we also do not support `--help`. The `hidden` option is under testing at the moment. Once ready, will be available in the app settings.
