### ISSUE TITLE
Adding caldav account loads (or tries to load) all available calendars of added account by default

### ISSUE THREAD

**Issue by wexi79** [marcoancona/MineTime#157]
When trying to add our company caldav account, all of the available calendars are being loaded, not just my personal one, even if iI try to add the account by the specific url of my personal calendar. This of course causes the software to hang as we have approx 200 calendars that are visible.

So we probably would need the option that you could add the calendars to be loaded after adding the account instead of trying to load everything.

**Comment by wexi79** [comment]
I would not classify this as an "enhancement" but rather a design flaw as currently this makes the calendar unusable if you try to add a CalDAV calendar that's located on a server that hosts a large amount of calendars. Now the software starts to sync the events of all calendars that it finds after adding the account and it never gets it done due to the vast amount. It is not possible to access the account settings (and define the calendars you want synced) during this as the software is hung up on the syncing attempt.

**Comment by wexi79** [comment]
Also if I leave MineTime to try and get all the calendars synced, after a while it just crashes.

**Comment by marcoancona** [comment]
We have just released 1.7.1 with improvements regarding this issue. Now CalDAV calendars that the user has access (but of which he/she is not the owner) are added to MineTime as "disabled". This means they appear in the calendar list but the sync process does not start by default.

This is the first step towards a full solution of enabling the user to select the calendars to attach during the account linking phase.

**Comment by wexi79** [comment]
Nice, I will try the latest version out

**Comment by wexi79** [comment]
Unfortunately, this does not seem to work. I removed the older version of MineTime and all the config data and installed the latest version but still after adding the CalDAV account using the following url format:

https://ourdomain.com/dav/my.user@ourdomain.com/Calendar

MineTime starts to go through and syncing the events of the shared calendars using the following urls:

https://ourdomain.com/dav/my.user@ourdomain.com/Firstname1%20Lastname1
https://ourdomain.com/dav/my.user@ourdomain.com/Firstname2%20Lastname2
...

So it seems that the disabling is not working as it should...

**Comment by marcoancona** [comment]
Do you manage to reach the point when you see the list of calendars being synced (as for the image below)? In this case, do all calendars appear with "owner" rights and "enabled"?

![image](https://user-images.githubusercontent.com/2278117/69151755-898c2480-0adb-11ea-8d39-4c4f304c8f3c.png)

**Comment by wexi79** [comment]
Due to the large amount of shared Calendars I cannot get to the account settings after adding the CalDAV account but I can see from the console that MineTime is getting the events of all the calendars. Also at some point if MineTime does not crash I can see the events of all the calendars in the calendar view.

**Comment by marcoancona** [comment]
The just-released 1.7.3 starts syncing for a maximum of 3 calendars when a DAV account is connected.  This should avoid the overloading and give you access to the settings where you can select which calendars should be enabled.

**Comment by wexi79** [comment]
Nice, I will test the newest version and report if I encounter any problems.

**Comment by wexi79** [comment]
Tested, and now I'm able to set only my own calendar as active. Managing the calendars is still really laggy though, when I click the checkbox to activate/deactivate a calendar it takes about 15 seconds or so for the checkbox to change state.

**Comment by marcoancona** [comment]
Continue tracking the performance issue in #175. Closing this.
