### ISSUE TITLE
1.7.1 not properly syncing with iCloud

### ISSUE THREAD

**Issue by ChristianSch** [marcoancona/MineTime#158]
Hi,

The syncing works when I create an entry in MineTime, but deleting it on my iPhone or creating one on an iPhone does not get synchronized to MineTime. Let me know if you need any further infos.

**Comment by marcoancona** [comment]
We cannot reproduce this issue with our iCloud test account. Please notice that CalDAV accounts are syncronized every 30 minutes if no additional sync is triggered manually. You can try with CTRL/Cmd+R or by clicking the circular arrow that appears next to the calendar name (on the Calendars tab of the sidebar). Please let me know if this does not help.

**Comment by marcoancona** [comment]
Closing to due lack of activity. Feel free to comment if the problem persists.
