### ISSUE TITLE
Waiting for email verification.

### ISSUE THREAD

**Issue by tomektoja** [marcoancona/MineTime#165]
I have a problem like in title. Everytime even if I reinstalled app I get a waiting for email verifictaction notification. There is no email in my gmail sent from you to verify account. How can I force Minetime to send me verification link? 
![Screenshot_20191223_090324](https://user-images.githubusercontent.com/35118026/71344578-363a4580-2563-11ea-9f0a-5adfa7d035fe.png)

**Comment by marcoancona** [comment]
This should be fixed by now. Closing.
