### ISSUE TITLE
Location suggestions is not cancellable, prevents saving

### ISSUE THREAD

**Issue by flg** [marcoancona/MineTime#169]
Hello,

The location suggestion "window" cannot be cancelled or ignored and is blocking access to whats underneath like the Save button.

See attached picture: ![bug](https://user-images.githubusercontent.com/325736/73168416-11a13280-40fa-11ea-958e-5d765eb9597d.png)

You can reproduce like this:
Create a new event, type something in the location, suggestions appear. If you don't want to accept any of these suggestions (in my case locations are internal "building-room" so there is no chance that suggestion will help), you cannot save the event because the Save button is hidden underneath.

I guess the window should disappear on a simple ESC key stroke, or any click outside it.

Cheers

**Comment by marcoancona** [comment]
This is now fixed.
