### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by nickriches** [marcoancona/MineTime#176]
As a fan of the Fantistical calendar on Mac, I've been looking for an equivalent on Windows and this is the first thing I've found which comes anywhere close. It's really great. But there's one thing which is lacking - a decent set of shortcut keys. You have added a few based on previous requests, to cycle forwards and backwards. I had to find these by searching through the GitHub site, and I wouldn't have known about them otherwise. However, as far as I can see there are none to switch between views (week, month etc.). It would be great to have a separate tab under Options where the user can specify shortcut keys for a variety of different operations, including switching between calendar views.

**Comment by marcoancona** [comment]
Hi,
Thanks for the feedback. This is already in our roadmap.
I think it is worth opening a discussion about which shortcuts are more useful. Do you have any other frequently used one besides switching views?

**Comment by nickriches** [comment]
Thanks for responding. For me the main shortcuts are;

1. Focus on create event window (already implemented)
2. Forward / back (already implemented, but not all keyboards have page up / page down)
3. Change view (Not implemented. This could be straightforward toggle, or different keys for different views, e.g. w = week, m = month).

In addition, a great feature would be to allow different sets of calendars and link these to shortcut keys (e.g. a set of calendars related to work events, and a set of calendars related to social events).

Finally, it'd be really good if shortcut keys can be set by the user. I particularly like google shortcuts (e.g. j/k for forward/back, / for focus on search bar, c = create event). I already use these in my email, and it would be great if I could use the same shortcuts in my calendar.

**Comment by nickriches** [comment]
P.S. other useful shortcuts are Jump to Today, and Find Event. It would be great if the google calendar shortcut keys could be chosen using a single option (NB Microsoft Outlook online takes this approach)

**Comment by marcoancona** [comment]
- ESC key to cancel new event creation
- Fix 'command+space' to open the Assistant sidebar (sometimes the sidebar opens and closes immediately)

**Comment by marcoancona** [comment]
> P.S. other useful shortcuts are Jump to Today, and Find Event. It would be great if the google calendar shortcut keys could be chosen using a single option (NB Microsoft Outlook online takes this approach)

@nickriches Find event is already implemented as CTRL+F, is this what you meant?

**Comment by marcoancona** [comment]
New shortcuts implemented in 1.8.5. For a list see https://github.com/marcoancona/MineTime/releases/tag/v1.8.5
