### ISSUE TITLE
Caldav connection to zoho.com

### ISSUE THREAD

**Issue by iagomosqueira** [marcoancona/MineTime#18]
I am trying to use the new caldav connection capacity with https://calendar.zoho.com. I have tried both to connect directly to https://calendar.zoho.com/caldav, as it is done in Android clients and on OSX, and to individual calendar addresses, as it is done in Thunderbird Lightning.

I get a message about failed authentication, with the same credentials (email and password), that work in other apps.

Any suggestion on what to look for?

**Comment by marcoancona** [comment]
Thanks for pointing out. We have just released MineTime 1.1.2 that solves the problem. If a few minutes an update button should appear on the main view of MineTime (restart of the app might be necessary). For zoho.com, please use the Server URL https://calendar.zoho.com/caldav

**Comment by iagomosqueira** [comment]
Perfect, working now. Many thanks
