### ISSUE TITLE
Hyperlinks in location field are not clickable or copyable

### ISSUE THREAD

**Issue by wexi79** [marcoancona/MineTime#180]
If the location field contains a hyperlink, I cannot click on it and open the URL. I also cannot select the link text and copy it. This of course is extremely annoying as online meeting links are quite often in said field.

MineTime 1.7.6 on Ubuntu Linux.

**Comment by arnaudon** [comment]
Agree, having this feature would be very convenient!

**Comment by leviadam** [comment]
Really need this feature. Makes life really hard, keep having to go back to google calendar just to open a meeting.

**Comment by marcoancona** [comment]
We have fixed this in 1.8.0. Now the text in the location field can be copied. Feel free to comment if the problem persists.

**Comment by leviadam** [comment]
Thanks! This is a real improvement. 
If you can make URLs clickable it will be even better :)
