### ISSUE TITLE
Send invites on event creation

### ISSUE THREAD

**Issue by carderne** [marcoancona/MineTime#182]
It's likely that I'm misunderstanding the MineTime workflow! With Thunderbird and Outlook webmail, when I create an event, all invitees (email addresses) are automaticcaly emailed with an ics or similar to add it to their calendar.

How do I achieve this with MineTime, or what should I be doing instead?

Edit: I'm using iCloud for my calendar account.

Edit 2: Similarly, is there any way to 'accept'/'decline'/'maybe' meetings? I feel like I'm trying to force the wrong paradigm onto MineTime.

Edit 3: The sending invites issue seems to be specific to iCloud, as it worked with a CalDAV account.

**Comment by marcoancona** [comment]
Invitations are automatically sent for every event created. We cannot reproduce the problem with iCloud. Can you confirm that the problems still persist?

**Comment by carderne** [comment]
Sorry I can't help, I stopped using MineTime because of this. Very possibly something specific to my setup...
