### ISSUE TITLE
Failure to login with Gmail

### ISSUE THREAD

**Issue by untoldone** [marcoancona/MineTime#183]
Installed application today, tried to login with gmail account -- after selecting google, then choosing an account + clicking "allow", the signin screen then seems to hang when being sent back to the requesting site. Quite a while later the page returns:

"Authorization failed. Please try again or contact us if the problem persists." at the url:
http://127.0.0.1:57416/?code=[REMOVED]&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/calendar%20openid&authuser=0&prompt=consent

and in app i receive the message "An error occurred during the authorization process. Please try again or contact us if the problem persists"

I tried to login with Windows 10 + Firefox as the default browser.

**Comment by untoldone** [comment]
Tested with Chrome as login browser as well with same results ... also tried disabling windows firewall which also didn't work

**Comment by marcoancona** [comment]
Thanks for reporting this. It looks like the browser cannot communicate back to MineTime once the login has succeeded. We are investigating this issue, but at the moment we cannot reproduce it on our Windows machine.

**Comment by untoldone** [comment]
Is there any logging I can provide to help reproduce? Anything I can do to help debug?

**Comment by K3taK3rm1t** [comment]
Same here using Firefox 75.0 on Kubuntu 19.10.
I've tried deleting the files in ../.config/MineTime and reinstalling, but didn't solve. If you need any other info let me know.
Thanks in advance!

**Comment by untoldone** [comment]
@marcoancona more than happy to provide logs, run a debug build, or do more in depth analysis if I'm able to get you more details that could help figure out what is needed to reproduce this. I've tried other Google GSuite accounts on the same computer with the same results.

This is on a clean + fully updated version of Windows 10 with Firefox doing the oauth side. When checking the resource monitor, I see MineTime successfully opens a local port temporarily which is also then not being blocked by a firewall. I am able to connect to the local server, but it hangs when redirecting back after completing the gsuite oauth process. If I refresh after the authentication has failed at the localhost side -- it returns immediately with the error message.

This all works fine on my mac on the same network conditions.

**Comment by marcoancona** [comment]
We have just released 1.8.0 with an improved OAuth pipeline. It would be useful to know if this solves the problem on Windows.

**Comment by untoldone** [comment]
Just gave it a try -- works great now. Thanks!
