### ISSUE TITLE
Cannot login to Office/Microsoft365 account that is using SSO

### ISSUE THREAD

**Issue by wexi79** [marcoancona/MineTime#185]
Out company just migrated from Zimbra to Microsoft 365 and we are using SSO; Minetime cannot login to the calendar account. Setting an app specific password for the account in Azure is not possible as we are not using 2-step verification. This would be an important feature as SSO logins are commonly used.

**Comment by gdr3941** [comment]
Same issue here; running 1.8.2 and unable to initially authenticate / connect to my Office365 account.

**Comment by marcoancona** [comment]
Hi! Version 1.8.4 introduces OAuth for Office 365 (using "Sign in with Microsoft"). This should allow to connect accounts with 2FA or SSO when creating an app-specific password is not possible. Feedback is welcome.

**Comment by wexi79** [comment]
Nice! I will test and report any possible issues.

**Comment by gdr3941** [comment]
Yes confirmed it now works great, thank you!
