### ISSUE TITLE
Color-blinded compatible colors for participants

### ISSUE THREAD

**Issue by BrunoSpy** [marcoancona/MineTime#197]
Thx for this great app !
Would it be possible to change the color of the participants of an event to something more compatible for color-blinded people. At the moment, it is really impossible to distinguish those who have declined the event from those who have accepted.

**Comment by marcoancona** [comment]
This is indeed important! In 1.8.4 we have added ticks and cross icons to indicate the participation status. Does this help?

**Comment by BrunoSpy** [comment]
Yes that's great! Thx !
