### ISSUE TITLE
Add support for generic caldav server

### ISSUE THREAD

**Issue by b3** [marcoancona/MineTime#2]
Everything is in the title. In order to be wide spread the first thing to add, IMHO, is support for generic caldav server.

Many caldav server are available in the free and open source world. A list of such software is available at https://wiki.debian.org/Groupware.

[Nextcloud](https://nextcloud.com) and [Cozy](https://cozy.io) could be added to this list.

**Comment by marcoancona** [comment]
Agree. We are already working on this.

**Comment by marcoancona** [comment]
Available starting from 1.1.0
