### ISSUE TITLE
[enhancement] Minimize to tray on Linux

### ISSUE THREAD

**Issue by paulomanrique** [marcoancona/MineTime#20]
As the title says, it would be awesome to minimize it to tray. At least on Ubuntu Linux with Unity, "Hide Mimetime", or the close button just minimizes to the task bar.

**Comment by Tamriel** [comment]
It works on Manjaro for me with the menu entry "hide window".

**Comment by paulomanrique** [comment]
Now the menu entry is gone, and the option on the tray icon just minimize do task bar =(

**Comment by rauferd** [comment]
I can confirm that the minimize to tray does not work using MineTime 1.3.2 and XFCE 4.12 (either with or without GNOME tray).

**Comment by ithinkmatt** [comment]
I would also like to set MineTime to startup minimized on startup in Ubuntu.

**Comment by paulomanrique** [comment]
It's almost one year since this feature stopped working. Any chance to get this fixed? It's really the only thing that keeps most people from using MineTime.

**Comment by nickallevato** [comment]
same

**Comment by Sparsa** [comment]
I am also facing this problem in Manjaro KDE, any solutions?
