### ISSUE TITLE
Current time indication is broken

### ISSUE THREAD

**Issue by struk3lj** [marcoancona/MineTime#203]
As seen in the screenshots below the current time indication (red line across the calender events)) is broken. It doesn't go all the way from the left to the right corner.

_**WEEK View**_
![image](https://user-images.githubusercontent.com/33715254/87280552-90482b80-c4f2-11ea-898f-8d38587f73d2.png)

**_10 day view_**
![image](https://user-images.githubusercontent.com/33715254/87280614-a229ce80-c4f2-11ea-8fb2-d1c55a03fabf.png)

**Comment by marcoancona** [comment]
Fixed in 1.8.4. If the problem persists feel free to leave a comment here. Thanks for reporting.
