### ISSUE TITLE
Zoom conference information not displayed when host uses GCal conferences feature.

### ISSUE THREAD

**Issue by phodamentals** [marcoancona/MineTime#207]
As the title states, when a meeting host uses the GCal conferences add-on when creating an calendar invitation (in this case Zoom), the conference information does not surface in the Minetime app. The meeting info shows up when the host has the info in the meeting details, of course though.

Is it possible to get the below info appear in Minetime?
![zoom_gcal](https://user-images.githubusercontent.com/3144570/87613458-00150c80-c6d3-11ea-91a8-e1f003f97b8f.png)

**Comment by marcoancona** [comment]
Hi, thanks for reporting this.
Zoom information should be displayed, are you using 1.8.3?

**Comment by phodamentals** [comment]
@marcoancona thanks for the swift response. Yes, I am running 1.83. Upgraded from a previous version. Would re-syncing or removing and adding the calendar accounts help at all? BTW, I am running the Linux version.

![Screenshot from 2020-07-17 20-14-08](https://user-images.githubusercontent.com/3144570/87841317-2c16c600-c86a-11ea-8c14-7f1286266162.png)

**Comment by marcoancona** [comment]
Visualizing Zoom data was introduced in 1.8. All events synchronized before the update won’t show the information. You can use the “Reset data” button to trigger a new full sync. Let me know if this helps.

**Comment by phodamentals** [comment]
@marcoancona That did the trick. Thank you.
