### ISSUE TITLE
Tags not editable in verson 1.8.2

### ISSUE THREAD

**Issue by debugzing** [marcoancona/MineTime#208]
I can't edit the tags anymore. I can create new tags but they are all assigned random color and New Category as title. Also I noticed the Add /Edit tag dialog box is hidden behind Add tag pop-up. 
![Screenshot from 2020-07-21 13-39-43](https://user-images.githubusercontent.com/49555830/88031881-d6d50000-cb5a-11ea-8c03-f994347049f6.png)

**Comment by marcoancona** [comment]
We are about to release a fix for this. In the meanwhile, you should be able to edit tags as usual if you access the Tag Editor from the left sidebar instead of right-clicking on the event.

**Comment by marcoancona** [comment]
Fixed in 1.8.4. If the problem persists feel free to leave a comment here.

**Comment by debugzing** [comment]
Thanks, happy with the workaround suggested. Keep up the good work!
