### ISSUE TITLE
Open In Background

### ISSUE THREAD

**Issue by ibrokemypie** [marcoancona/MineTime#209]
Being able start applications on login is pretty annoying without a way to start them minimized, having 5 different windows pop up ever time you log in is no fun.
Adding a command line option to start minetime minimised to tray would be great

**Comment by marcoancona** [comment]
Oh which operating system are you running MineTime? We are currently testing the `--hidden` parameter to run in the background. You can give it a try.

**Comment by ibrokemypie** [comment]
On linux, that works, thankyou!
