### ISSUE TITLE
1.8.4 forgot all calendars

### ISSUE THREAD

**Issue by ChrisJefferson** [marcoancona/MineTime#212]
I've upgraded to 1.8.4 and all my calendars have disappeared

**Comment by marcoancona** [comment]
It seems MineTime cannot connect to the internal database. On which operating system are you using MineTime?
Please try the following:
- quit MineTime completely (kill any process containing "MineTime" or "mongod" in the name)
- restart the computer
If the problem persists, please uninstall and install MineTime again.

**Comment by ChrisJefferson** [comment]
Uninstalling + Reinstalling seems to have fixed the problem (it still forgot all my calendars, but I could at least re-add them).
