### ISSUE TITLE
1.8.4 hangs when adding new calendar

### ISSUE THREAD

**Issue by ChrisJefferson** [marcoancona/MineTime#213]
I tried adding a new calendar via 'office 365' or outlook, in both cases after giving my email address + password minetime just hangs (left for at least 5 minutes).

**Comment by ChrisJefferson** [comment]
also "sign in with microsoft" gets stuck too, my web browser just displays "trying to sign you in", but I can log in fine to office365.

**Comment by marcoancona** [comment]
I close this because I believe it has the same route cause of #212
