### ISSUE TITLE
can't add Google calendar account.

### ISSUE THREAD

**Issue by lingtongwang** [marcoancona/MineTime#22]
try to add google account for several times, but minetime have no react. I checked "Apps with access to my account" in google account info, not find minetime

**Comment by marcoancona** [comment]
Sorry for the late reply. We didn't receive other notices about similar issues. Which version of MineTime and operating system are you using? Are you behind a firewall or need a proxy to connect? Could you describe in details what happens when you try to connect your Google Calendar?

**Comment by lingtongwang** [comment]
I found that it's because i use proxy connect. I stop the proxy then connect success. Thank you!

**Comment by ithinkmatt** [comment]
Minetime is working on my desktop running Ubuntu Budgie 18.10, but I am unable to add my Google G Suite account to MimeTime on my laptop, also running Ubuntu Budgie 18.10.

It goes through the process with Google to allow access, but no account or calendar is added when adding allow. However, everything worked perfectly on my desktop when setting up.

I have removed the package multiple times. No idea what to do next.

Please help to resolve.
