### ISSUE TITLE
Improve dark theme

### ISSUE THREAD

**Issue by murakami-marco** [marcoancona/MineTime#226]
Hi MineTime team!!

On dark theme, the links are unreadable.

![image](https://user-images.githubusercontent.com/823462/92941463-034c2080-f416-11ea-8713-ce2036a30cce.png)

I would be nice to change a bit the links color.

Thanks in advance!!!

**Comment by Gameniti** [comment]
Yep I agree with this one. I don't know if this is a real phone number, but I would be careful with this.

**Comment by murakami-marco** [comment]
> Yep I agree with this one. I don't know if this is a real phone number, but I would be careful with this.

Thanks about the phone number. It's not relevant. It's an old meeting but nonetheless, thanks!!! Already changed
