### ISSUE TITLE
Save state of left sidebar

### ISSUE THREAD

**Issue by Tamriel** [marcoancona/MineTime#23]
Clicking the burger icon in the top left hides the sidebar.
When I restart the app, the sidebar is visible again.
It should stay hidden.

In my opinion the sidebar clutters the view, since it provides no features for me.
However, when adding an event, the sidebar appears and stays.
It would be nice, if the the animation could be turned off, since it is distracting.

**Comment by marcoancona** [comment]
Status is now preserved on restart in 1.2.0.
