### ISSUE TITLE
Office365 MFA Support

### ISSUE THREAD

**Issue by flemingm** [marcoancona/MineTime#234]
OAuth 2.0 for authentication and authorization support is needed.

https://developer.microsoft.com/en-us/office/blogs/end-of-support-for-basic-authentication-access-to-exchange-online-apis-for-office-365-customers/

is this on someone road map?

**Comment by marcoancona** [comment]
Hi! OAuth is already implemented in the latest versions. Please let me know if you find any issue with it.

![image](https://user-images.githubusercontent.com/2278117/94444453-a044e280-01a6-11eb-8cf0-058d06c98703.png)

**Comment by marcoancona** [comment]
Close due to inactivity. Feel free to leave a comment if the problem persists.
