### ISSUE TITLE
Add option to hide early hours

### ISSUE THREAD

**Issue by Tamriel** [marcoancona/MineTime#24]
In week view, the user wants to hide e.g. the hours 0 to 8.

**Comment by marcoancona** [comment]
Thanks for your feedback. This is already possible in the app settings -> Agenda display.

**Comment by Tamriel** [comment]
Oh. Then I think the label "Agenda display" is wrong, since it's not for the agenda view but for the day and week views?

**Comment by marcoancona** [comment]
Yes this will be fixed in the next release
