### ISSUE TITLE
Add command line options to show and hide the window

### ISSUE THREAD

**Issue by Tamriel** [marcoancona/MineTime#25]
e.g. `minetime hide`.
With this, one can set a keyboard shortcut to show and hide MineTime.

**Comment by Tamriel** [comment]
No. But e.g. the software [quod libet](https://quodlibet.readthedocs.io/en/latest/guide/interacting.html#controlling-the-player) is able to understand command from the command line.

**Comment by marcoancona** [comment]
I see. However in this case registering a global shortcut would make more sense. I will close this and update the title on another of your issue.
