### ISSUE TITLE
White page when loading with session

### ISSUE THREAD

**Issue by LoosGuccreen** [marcoancona/MineTime#257]
Hello

Since 1.9.3 of Minetime it seems the app is often "blank" when starting with the session of my computer (it did not to that previously). It looks like some module hasn't loaded properly.

If I manually close the app and reopen it again it works fine.

I'd love to give more details than that but I don't exactly know what could help or how to generate a debug log.

I'm on Kubuntu 20.04.1 LTS and I run the app using AppImage.

Thanks !

![2021-01-19_09-43](https://user-images.githubusercontent.com/6335020/105009549-e5816e80-5a3a-11eb-9f43-3b73727c2a2c.png)

**Comment by marcoancona** [comment]
Hi!
Thanks for reporting. Is it also happening in 1.9.4?

**Comment by LoosGuccreen** [comment]
Hello, thanks for the feedback
Good news, it doesn't !
I got the update quickly after creating this issue but was observing if the issue persisted. So far so good it seems to have been fixed in the process.
