### ISSUE TITLE
some "all-day" events shifted to the wrong day(s)

### ISSUE THREAD

**Issue by gwert** [marcoancona/MineTime#27]
Some of my "all-day" events coming from google and iCloud calendars are being shifted a day early.  I'm guessing it's a timezone quirk (UTC vs. New York), but it doesn't seem to happen to all of them.

**Comment by marcoancona** [comment]
Hi! Thanks for pointing out this issue! Is that occurring for events that you create in MineTime (that are shown on a shifter day on the Google calendar web version) or the other way around?
Also, if it happens you understand what differentiate events that do and do not present this problem, that would be very useful.

**Comment by gwert** [comment]
None of them were created in MineTime, but they appear in MineTime shifted a day early.  They were created on one of the following: the Mac OS X Calendar app, iOS, or the Google calendar web version -- and one recent example I'm looking at now was auto-generated by Google scanning through an email.  I'll let you know if I figure out a pattern or sequence that causes this sometimes and not others.

**Comment by AgentSource** [comment]
Same issue... def appears to be an issue with the start and end date. I created an event via Minetime and via my phone and both get shift back a day. Had a look what Google returns via list API and the key for start and end return — just finished an invoice app and had similar issues... this is only a guess, hope this helps

**Event with start and end times**
`{
 "kind": "calendar#event",
 "status": "confirmed",
 "created": "2018-03-21T19:22:45.000Z",
 "updated": "2018-03-21T19:22:45.746Z",
 "summary": "test event 1",
 "creator": {
  "email": "",
  "displayName": "",
  "self": true
 },
 "organizer": {
  "email": "",
  "displayName": "",
  "self": true
 },
 "start": {
  "dateTime": "2018-03-24T10:00:00-05:00"
 },
 "end": {
  "dateTime": "2018-03-25T09:00:00-05:00"
 },
 "transparency": "transparent",
 "sequence": 0,
 "reminders": {
  "useDefault": false
 }
}`

**All day event**
`{
 "kind": "calendar#event",
 "status": "confirmed",
 "created": "2018-03-21T19:22:45.000Z",
 "updated": "2018-03-21T19:22:45.746Z",
 "summary": "all day event",
 "creator": {
  "email": "",
  "displayName": "",
  "self": true
 },
 "organizer": {
  "email": "",
  "displayName": "",
  "self": true
 },
 "start": {
  "date": "2018-03-24"
 },
 "end": {
  "date": "2018-03-25"
 },
 "transparency": "transparent",
 "sequence": 0,
 "reminders": {
  "useDefault": false
 }
}`

**Comment by marcoancona** [comment]
We will release a fix for this asap

**Comment by marcoancona** [comment]
Version 1.1.4, that fixes the problem, is now available. Feel free to reopen if the problem persists.

**Comment by gwert** [comment]
Even after upgrading to 1.1.4 and resetting the calendar data, the problem still persists for me.  I don't think I have the right permissions to reopen the issue.

**Comment by marcoancona** [comment]
Additional fix in 1.2.0. I'll keep this open for feedbacks.

**Comment by gwert** [comment]
Progress!  Now it looks like the all day events coming from both of my gmail accounts are correct.  However, most of the all day events coming from my iCloud account still show up a day early

**Comment by marcoancona** [comment]
Released 1.2.1 with fix for iCloud/CalDAV

**Comment by gwert** [comment]
All looks good for me now.

**Comment by marcoancona** [comment]
Thanks for the feedback. I will close this.

**Comment by gwert** [comment]
One more follow-up to this issue.  While the all day events are now displayed on the correct days and they can even be created correctly using MineTime, when I go back in to edit an all day event, the dates initially listed are shifted a day early and I have to fix them before making any edits.
