### ISSUE TITLE
Update on AUR repository

### ISSUE THREAD

**Issue by mfcarneiro** [marcoancona/MineTime#28]
I want to use MineTime more frequently and really looks promising.

But I use archlinux and the project are out of date (current version 1.0.11-1).

There is a way to update the AUR repo? Allowing me donwload and update the project?
![1524682074_1547_25042018_601x132](https://user-images.githubusercontent.com/13247083/39266309-0d953726-48a0-11e8-9493-67fa14fd83b7.png)

**Comment by oblednov** [comment]
You can edit the PKGBUILD file to pull the latest version instead of 1.0.11-1.

**Comment by mfcarneiro** [comment]
@oblednov Thanks for the tip!

I'll do that.

**Comment by marcoancona** [comment]
I'll close this as it seems a solution has been found.
