### ISSUE TITLE
Connected with Office365 but events are not syncing

### ISSUE THREAD

**Issue by rajan471** [marcoancona/MineTime#29]
For me MineTime is connected to office365 account. I am able to create events but they are not in sync. Say if I delete it from other app like outlook it will not sync. Also my old events are not appearing in the app.

**Comment by marcoancona** [comment]
Could you please try the latest release, 1.2.1?

**Comment by rajan471** [comment]
I figured it out. This issue is with Ubuntu 18.04. Now I switched back to Ubuntu 16.04 and most of the apps are working fine now.
