### ISSUE TITLE
Please add support for ICS files

### ISSUE THREAD

**Issue by Chaupeter** [marcoancona/MineTime#33]
Clicking on invitations sent via email or web link to add an event to a calendar.

**Comment by marcoancona** [comment]
We have just released MineTime 1.2.1 with support for ICS files. Feedbacks are welcome, in the meanwhile I will close this.

**Comment by didrip** [comment]
It works but only sometimes for some reason

- if dragging `ics` file on MineTime => works everytime. import popup shows up
- if double-clicking `ics` file (after setting file association in Settings > App > Default Apps > "Choose default apps by file type") => only works sometimes (mineTime opens but "import event popup does not show up)
- if clicking a link to `ics` file => same than above

Minetime 1.5.1 (default calendar set)
Windows 1809
