### ISSUE TITLE
Can we please have a larger selection of colours to choose from ?

### ISSUE THREAD

**Issue by Chaupeter** [marcoancona/MineTime#36]
The colour choice is too limiting for calendar creation can we please have a lager choice or the option to use the same colours as our Google Calendars ?  Thanks for your consideration.

**Comment by marcoancona** [comment]
Thanks for the suggestion. This was for (too) long in our backlog. We have just released 1.2.2 that enables free color selection for calendars and also imports colors from Google accounts when they are connected.
