### ISSUE TITLE
Integrate with Nylas mail

### ISSUE THREAD

**Issue by MelvinLoos** [marcoancona/MineTime#4]
Hi, first of all thank you for the awesome app. I have been looking for a decent lightweight calendar app for linux and this has worked like a charm. Next to lightweight it also has some really awesome features like the google style sentence-to-appointment feature.

Anyway, I am not sure if you are aware already but [Nylas mail](https://github.com/nylas/nylas-mail) is a opensource cross-platform mail app. It started as a client showcase for their mail server unification/standardization API but has gathered quite some praise and following over its lifetime. One of my (and others) main criticism on the app is the missing calendar. Which, even though they have the foundation ready for, still has not been added. A missing calendar this app seems to implement quite while.

Now I found both that app and this one because they have been build on electron so I was wondering, how awesome would it be if we could create a Nylas mail plugin based on the great work done on this project? Also by integrating with that app you would also be able to reach more types of mail servers and probably lower maintenance efforts. So what do you think?

**Comment by Chaupeter** [comment]
There is not much point in supporting Nylas Mail as development has stopped.  It has been forked to MailSpring.

**Comment by marcoancona** [comment]
Agree. Will close this.

**Comment by MelvinLoos** [comment]
there is actually two main forks that I know of of which Mailspring is the work of the original author. This fork is an actual project with a paid version and a business behind it. Also this issue was not so much a feature request as more of an attempt to discuss possibilities. 
Furthermore why would the forking of the original project make this idea pointless? It is still actively being developed in the forks so we can still make it compatible with those. If there is no interest in this than that would be a valid reason to close this issue, given reason not so much.
