### ISSUE TITLE
Can we please have an option to change the default notification time ?

### ISSUE THREAD

**Issue by Chaupeter** [marcoancona/MineTime#41]
Creating such an option will allow us to have a default notification time for timed events and a different notification for all day events such as birthday's, anniversaries  etc.  For example we might have a notification time of an hour or half hour for a timed event and maybe a day for a birthday or anniversary.

Thank you for your consideration.

**Comment by marcoancona** [comment]
This options is already available. Go to Settings -> Calendars -> Select one account -> Use the "more options" (3 dots) next to the calendar name to access Notification settings. 
This allows you to define default notification times for all events in a calendar.
