### ISSUE TITLE
Suggestion: context menu as popup next to event

### ISSUE THREAD

**Issue by mturley** [marcoancona/MineTime#44]
Hey there!  Still loving MineTime. Hope you don't mind the suggestions.

One thing I feel like I am missing, having switched to MineTime from the Google Calendar web interface, is the menu you get when you click on an event in Google Calendar. Being able to quickly delete an event with a little right-clicking menu or something, without having to pull open the left-side menu, would be much faster.

I'm sure my use case is a little strange, I like to use a special usually-hidden calendar to micromanage my time, so I do a lot of creating, moving and deleting events as my day changes. I basically use my calendar as a time-bound to-do list. So when I need to delete 4 events, currently in MineTime I have to click each one, move the mouse to the left, click Delete, mouse back and forth across the screen for each event (also using MineTime on a large monitor). The right-click menu would keep that operation localized to the area around the event, not much mouse movement at all.

I'm only picturing a tiny menu with two or three choices. "Edit, Delete". Edit just opens the side pane like double clicking an event does now.

Obviously I am an insane person and I should just be less lazy. But these little annoyances add up and I sometimes go back to Google Calendar web, for this use case. I love MineTime and I wanna stay in it!

If and when you go open source, I will totally fork and help you improve this app.

**Comment by mturley** [comment]
Ah, I hadn't thought of that ! haha. Simple enough.

**Comment by marcoancona** [comment]
New context menu to delete and tag events added in 1.4.0.
