### ISSUE TITLE
Synchronize secondary Exchange calendars

### ISSUE THREAD

**Issue by diegoferigo** [marcoancona/MineTime#46]
Exchange has the possibility to add secondary calendars, for example:

<img width="478" alt="spectacle k15230" src="https://user-images.githubusercontent.com/469199/41897804-9cca4c52-7928-11e8-97ff-ab23ad0d4851.png">

For some reason they do not get synchronized from MineTime, is this a supported feature?

I already tried to delete the exchage account and add it again after I added the new calendar from the web interface. I am using the last 1.3.0 version.

**Comment by marcoancona** [comment]
Secondary Exchage calendars should be synchronized by MineTime, but calendars are listed only the first time an account is connected. Can you please try to delete your account and connect it again?

**Comment by diegoferigo** [comment]
@marcoancona Thanks for the super quick reply! It still doesn't show up. I did the following steps:

- Disabled current configuration:
  ```
  mv $HOME/.config/.MineTime{,.bak}
  ```
- Relinked only the Exchange account

If it is important, from the web interface I had to use the option `From directory` and not `Secondary calendar`. I'm not sure about the differences concerning the backend side.

**Comment by diegoferigo** [comment]
I figured out I was missing a step. Despite the calendar was added from the web interface of my account, manually adding it also in MineTime is necessary (even after logging out / relinking the account). This can be done from here:

![calendar](https://user-images.githubusercontent.com/469199/42363096-6b62ba5c-80f6-11e8-8d94-bc956cc88d4d.jpeg)
