### ISSUE TITLE
suport app.window.hide

### ISSUE THREAD

**Issue by ocehugo** [marcoancona/MineTime#47]
Hi,
Every time I press my linux shortcut to hide the window I got in the log app.window.hide but nothing happens.

**Comment by marcoancona** [comment]
What distribution of Linux are you using? Which version of MineTime?

**Comment by binshengliu** [comment]
Maybe the same issue. Unable to hide the window but I didn't see any log output.

MineTime 1.4.10. Debian with i3wm.

**Comment by Mehonoshin** [comment]
@ocehugo how did you install minetime on gentoo? Do you have overlay published somewhere?

**Comment by ocehugo** [comment]
Installed from source. Not using anymore so ymmv
