### ISSUE TITLE
Ability to delete appointment created by another user

### ISSUE THREAD

**Issue by Leekingshott** [marcoancona/MineTime#49]
When I have an appointment (Office365) which I have previously accepted from another user (again on O365), I am unable to delete this appointment.

This is certainly case for repeating appointments - not sure if it is also the case for one-off appointments.

Linked to this - the Assistant does seem to recognise 'Cancel' or 'Delete' as options for appointments...

**Comment by marcoancona** [comment]
You can cancel/refuse invitations by clicking on your name in the attendee list. Are you referring to this operation?

**Comment by marcoancona** [comment]
Close due inactivity.
