### ISSUE TITLE
Arch Linux AUR Repository - is not being updated

### ISSUE THREAD

**Issue by egorbelibov** [marcoancona/MineTime#51]
I have noticed that the version in the AUR Repository is stuck in the 1.0.11-1 version of the app. Could you guys update it, please? I really love the product, but it's not convenient to install it manually every time a new version comes out.

**Comment by VegaDeftwing** [comment]
I don't think they're the ones maintaining the AUR package, I'm not sure though. For now the appimage works.

**Comment by marcoancona** [comment]
I confirm. The AUR package was not created by us we do not plan to update it. Our current auto-update mechanism works only on macOS and Windows, unfortunately. We are looking into solutions to bring auto updates on Linux too, but it will be a cross-distribution solution like #42 
Sorry, I'll close this as wont-fix.
