### ISSUE TITLE
Where does one enter the verification code?

### ISSUE THREAD

**Issue by johnperry-math** [marcoancona/MineTime#53]
From the verification email I've received it seems that MineTime should automatically request the verification code the next time I start it:

> Run MineTime and copy the following code. MineTime will detect it automatically.

... only it didn't. A box at the bottom of the screen says it's "Waiting for email verification. Please check your inbox. OPEN PROFILE" but when I open the profile it didn't ask for anything. I see a yellow circle with an exclamation point next to "Your Profile" and hovering over that says, "Email verification pending" but there's no place to enter it.

Finally I realized that this meant "copy the following code **to your clipboard**." This was a bit of a hassle because I almost never use my gmail account, so I access it only from my phone, not from my laptop, where MineTime was located. What I did was type the code into an application, highlight it, and copy it to the clipboard. Sure enough, MineTime recognized it immediately and now I'm verified.

At the very least, the wording here leaves something to be desired for idiots like me who struggle with reading comprehension. But I would also suggest leaving a place for the code to be entered directly for weirdos like me who don't access our accounts everywhere.

**Comment by marcoancona** [comment]
Thanks for pointing out the ambiguity. We changed the email template to be more clear.
We will also add an input box in a future release.
