### ISSUE TITLE
Cannot load calendar content.

### ISSUE THREAD

**Issue by lm808** [marcoancona/MineTime#55]
Successful at log in and seeing the individual calendars. However the contents of the calendars cannot be loaded and they just keep spinning in the side bar.

Accounts tried: iCloud, Office 365.

MineTime version 1.3.0 and 1.3.2.
Arch Linux, up to date. XFCE4. MineTime installed by extracting the deb package.
Explicitly installed libxss 1.2.2-3 to resolve runtime dependency.

Previously worked on Xubuntu 14.04 LTS.

**Comment by marcoancona** [comment]
Thanks for your pointing out. Are you working behind a firewall or a proxy? Do you see any error if you run MineTime from the terminal?

**Comment by lm808** [comment]
Yes. Just tried it. Please see text file attached with console outputs.
For this, I simply started MineTime and chose to add a new account. With a successful log in, I can see all the calendar names in the side bar, but no actual calendar content was loaded, there is an ever-spinning animation next to the calendar names.
[console_outputs.txt](https://github.com/marcoancona/MineTime/files/2297635/console_outputs.txt)

**Comment by marcoancona** [comment]
I agree that the documentation should mention this. Have you tried with AppImage? We cannot maintain packages for all distributions, but we are working to improve the universal AppImage and also considering the distribution of a snap package that would provide auto-update.
