### ISSUE TITLE
Adding a CalDAV delegate calendars

### ISSUE THREAD

**Issue by rauferd** [marcoancona/MineTime#57]
Expected behavior: When specifing a CalDAV server only (e.g. `calendar.example.com`) the user's default calender should be used. When specifying a full URL, e.g. `calendar.example.com/caldav.php/conferenceroom1/calendar` this calendar should be used and NOT the user's default calendar.

Actual behavior: When adding a new CalDAV account, MineTime _always_ automatically selects and adds the user's default (own) calendar.
This is true even if the full URL to another calendar (another person's or resources' calendar) is given. It looks up the user's standard calendar on this server instead and use that instead of the specified calendar.

While I like the autodetection feature, it seems to be IMPOSSIBLE to add another calendar (not the user's standard calendar) from the same server, which makes MineTime useless for some rather common cases. For many CalDAV setups, users have read and write access to many shared calendars (rooms, machines, cars, colleagues, "public" calendars, etc.).

Using MineTime 1.3.2 on Debian Stretch and Windows 10.

**Comment by rauferd** [comment]
Note: I did read the somehow related issue https://github.com/marcoancona/MineTime/issues/19 , but I think that my case is different, since there is no error. Everything works as expected (by the programmer :-) ), but not as expected by me and all users having to share CalDAV calendars.

**Comment by marcoancona** [comment]
Hello,
we are working to fix some known problem with DAV calendars. We plan to release these features soon. Do you have a way to give us access to a test calendar that highlights this problem? If so, it would be helpful if you could email us the credentials so we can run a test.

**Comment by rauferd** [comment]
I send the credentials via e-mail.

I just noted that MineTime actually import all calendars **owned** by a user, not just his or her default calendar. Calendars owned by other users are definitely not imported, regardless of the user's permission for other calendars.

So MineTime must do some kind of autodetection, but it seems to be incomplete.

Regardless of the autodetection, I think that you still need a way to add a single calendar explicitly (or maybe an addition to the GUI allowing for the selection of calendars on a server :-) ). Consider the situation where a user has access to many calendars on a server, but only wants to manage one or few of them via MineTime.

You may want to take a look at the DAVDroid GUI which nicely asks for a selection of calendars when adding a new CalDAV user with access to multiple calendars on one server.

**Comment by marcoancona** [comment]
CalDAV delegate calendars are now available in beta in 1.4.0

**Comment by rauferd** [comment]
I can confirm that MineTime now automatically adds **all** calendars belonging to the specified username on that CalDAV server, not only the user's main calendar. This is better that before, but not a solution (yet). Would you kindly reopen the issue?

It is still not possible to select calendars and, most importantly, it is still not possible to add a calendar owned by another person or resource, regardless of the user's read and write permissions on the CalDAV server.

When entering the base URL of the server only, MineTime now nicely automatically finds and adds all of **my** calendars. When entering the full URL to someone else's calendar on the same server, MineTime does the same and adds all of **my** calendars (automatically), but not the resource/calendar **specified by the full URL**.

**Comment by marcoancona** [comment]
To add delegate calendars, please use the “+” button below the calendar list. Here you can enter a full calendar url. 

Yes, by default, MineTime imports all your calendars but you can then disable or delete individual ones if not interested in syncing those.

If this does not work, let me know and I will reopen the issue.

**Comment by christianparedes** [comment]
I have also another problem, using 1.4.1, I can reach some users from my organization but some other not. All users from organization have access to view each others calendars, but this seem not o work on minutiae (other calendar systems work) 
There must be a bug maybe on the way it reached for users. 
Error message: "Cannot access correctmail@domain.com"

**Comment by marcoancona** [comment]
Is this an Exchange server? If so, it would be helpful to know which version of Exchange your organization is running. 

Also, when you say “reach” other users, do you mean add their calendars as delegate calendars? Can you explain the steps that lead to the error message?

**Comment by christianparedes** [comment]
We are using Office365
1) manage user
2) select office365 account of our Organisation
3) add delegate... pressing +
4) on overlay I add email (username)
5) get error (on 30%) of cases I try with member of our Organisation...

I can provide you an account for you to test and debug...

Christian



On 18 Sep 2018, at 15:12, Marco Ancona <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this an Exchange server? If so, it would be helpful to know which version of Exchange your organization is running.

Also, when you say “reach” other users, do you mean add their calendars as delegate calendars? Can you explain the steps that lead to the error message?

**Comment by marcoancona** [comment]
A test account would be extremely useful to fix this.
You can email me directly at anconam [at] ethz.ch<http://ethz.ch>

Il giorno 18 set 2018, alle ore 11:33, Christian Paredes <notifications@github.com<mailto:notifications@github.com>> ha scritto:

We are using Office365
1) manage user
2) select office365 account of our Organisation
3) add delegate... pressing +
4) on overlay I add email (username)
5) get error (on 30%) of cases I try with member of our Organisation...

I can provide you an account for you to test and debug...

Christian



On 18 Sep 2018, at 15:12, Marco Ancona <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Is this an Exchange server? If so, it would be helpful to know which version of Exchange your organization is running.

Also, when you say “reach” other users, do you mean add their calendars as delegate calendars? Can you explain the steps that lead to the error message?
