### ISSUE TITLE
Loading of CalDAV calendar events fails if some are ill-formed

### ISSUE THREAD

**Issue by rauferd** [marcoancona/MineTime#58]
I saw this when adding CalDAV calendars, but only not with all of my calendars, only with two or three particular calendars.
How to reproduce or trigger the problem: ???

Expected behavior: Load all events from the calendar.

Actual behavior: Adding one of the critical CalDAV calendars, the spinner in the GUI next to the calendar name just keeps spinning. Some events are added to the calendar, but not all. The following error messages are printed at the command line (each a few hundred times):
> Moment Timezone has no data for W. Europe Standard Time. See http://momentjs.com/timezone/docs/#/data-loading/.
> Moment Timezone has no data for W. Europe Standard Time. See http://momentjs.com/timezone/docs/#/data-loading/.
> XXX
> [Function: t]
> YYY

and also, a little later a few hundred of these:

> [LOG] exception
> error:    error=Uncaught TypeError: Cannot read property 'start' of undefined, line=1, _remote=true

If required, I can provide access to this calendar.

Using MineTime 1.3.2 on Debian Stretch and Windows 10.

**Comment by marcoancona** [comment]
Hello,
yes a test calendar would be very helpful. You can email us the credentials. We are currently working to fix several issues with DAV calendars and this definitely looks like a bug.

**Comment by rauferd** [comment]
I suspect that the issue may be related to an incorrectly formated event with the following text (incorrectly) placed in the attendee section: `;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT;SCHEDULE-STATUS=1.2;=`

For one calendar I can confirm that removing this (and similar events) fixed everything, so that the calendar now loads fine.

This is definitely a client problem (although I cannot currently tell which client causes this problem). I still think that MineTime should handle such issues gracefully, i.e. drop the attendee information only -- or, at maximum, the entire event, but should _not_ stop loading the calendar.

**Comment by marcoancona** [comment]
MineTime 1.4.0 is now more robust to ill-formed events. Only these are skipped.

**Comment by rauferd** [comment]
I can confirm that loading calendars is now more robust (at least for me). Thanks you for the quick solution!

Also, I can confirm that I don't see these errors anymore:
> [LOG] exception
> error: error=Uncaught TypeError: Cannot read property 'start' of undefined, line=1, _remote=true


Nevertheless, upon adding a new CalDAV calendar I still see the following message more than 500 times:
> Moment Timezone has no data for W. Europe Standard Time. See http://momentjs.com/timezone/docs/#/data-loading/.

Maybe this is an entirely different problem... Should I open a new issue?
Except for the many messages, there seems to be no problem from the user's point of view. The imported event times are correct.

**Comment by rauferd** [comment]
Actually, I found a workaround:
Usually, it is not possible to add two accounts on one server (even though there is no error message, MineTime just doesn't add another account).

When asking the owner of another calender for his or her username and password, it **is** possible to add the same server again (with that other username and password). Then, the calendars of this other user are visible (and editable) in addition to my calendars.

However, this is certainly **not** the way calendar sharing is meant to work, plus there is no support for read-only calendars and private events. I just wanted to report my findings.

**Comment by marcoancona** [comment]
> Maybe this is an entirely different problem... Should I open a new issue?

I have opened #64 as this is a different issue.

> When asking the owner of another calender for his or her username and password, it is possible to add the same server again (with that other username and password). Then, the calendars of this other user are visible (and editable) in addition to my calendars.

Agree, sharing the credentials is a no-go. Please use the new "Add delegate calendar" function instead (accessible with the `+` button at the bottom of the account details view)
