### ISSUE TITLE
Enhancement: Sync calendar colors when using CalDAV

### ISSUE THREAD

**Issue by rauferd** [marcoancona/MineTime#59]
With CalDAV accounts, it is possible to sync calendar colors. It would be nice if MineTime could import those colors.

Hint: DAVDroid can do it. If you think about implementing this, you might want to take a look at their code: https://gitlab.com/bitfireAT/davdroid/

**Comment by marcoancona** [comment]
The next release will support custom tags/colors for each event, but synchronization with external services is still in progress...

**Comment by marcoancona** [comment]
Event colors are now available with 1.4.0 (but no sync yet).

**Comment by rauferd** [comment]
While I appreciate the support for _event colors_, the original request was for _syncing calendar colors_. All Apple products sync the colors of each _calendar_ across all devices.
All events show up in the calendar color (unless one is using event colors). Calendar colors were available in MineTime before, but they were chosen apparantly radomly, so the calendars looked very different for be because I am used to the color's meanings.

It is possible of course, to change the colors manually in MineTime, but syncing colors would be nice. When a user sets a calendar color deliberately, then there is no reason to assume that he or she would like to use a different color on another device.

**Comment by marcoancona** [comment]
Oh, I thought this was about the calendar *events* color. 
We fixed this in 1.4.1. Now, calendar colors for Google, CalDAV, iCloud and ics subscriptions are imported from the remote server when the account is linked. For already existing accounts, a relink is necessary in order to import the calendar colors.

**Comment by rauferd** [comment]
Confirmed working with MineTime 1.4.1 for the _initial import_ of new calendars only.

When I change the calendar in another application, the change is not reflected in MineTime unless I manually relink the calendar.

When I change the colors in MineTime they are not synced at all. Other devices still the the "old" color. 
When I click "RELINK", the colors stil remain the same, they are not updated/synced from the server again.

**Comment by marcoancona** [comment]
Yes, this is expected behavior. All calendars data, including color and display name, but also the list of calendars itself, are not updated if not using the Relink button.
Full, two-way sync is a feature in our backlog but has lower priority as these are rather rare operations.
