### ISSUE TITLE
Does not work with Office365

### ISSUE THREAD

**Issue by krishnakumarg1984** [marcoancona/MineTime#6]
Hi,

Minetime does not seem to be working with Imperial College's Office365 account.  username@ic.ac.uk

The username, password and server info that I entered are all correct. Yet, it fails to connect to the server.

**Comment by marcoancona** [comment]
Hi,
we have just released version [1.0.11](https://github.com/marcoancona/MineTime/releases), with improvements in Office 365 login. Could you check if this solves the problem?

**Comment by oserban** [comment]
I just tested version 1.0.11 and it works brilliantly with my office 365 account.

**Comment by marcoancona** [comment]
Thanks. I will close this. @krishnakumarg1984, feel free to reopen if you still experience issues.

**Comment by rajan471** [comment]
For me MineTime is connected to office365 account. I am able to create events but they are not in sync. Say if I delete it from other app like outlook it will not sync. Also my old events are not appearing in the app.
