### ISSUE TITLE
Cannot connect to any server using a self signed certificate: CalDAV (and others?)

### ISSUE THREAD

**Issue by rauferd** [marcoancona/MineTime#60]
How to reproduce: Add a new account (I tested CalDAV) that uses a server with a self signed certificate for TLS.

Expected behavior: Ask the user whether to trust the certificate.

Actual behavior: The account cannot be added. GUI error message: Authentication failed (even though MineTime never actually tried to authenticate.

Workaround: Start MineTime from a console with the following environment variable set: `NODE_TLS_REJECT_UNAUTHORIZED=0`
_This works for me, but it cannot be a permanent fix due to the security implication of diabling all certificate checks for node.js!_

Error message on the console:
> info:    Creating CalDAV account...
> warn:    CalDAV account creation failed with message=Bad status [0]: Error: self signed certificate
>     at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
>     at emitNone (events.js:105:13)
>     at TLSSocket.emit (events.js:207:7)
>     at TLSSocket._finishInit (_tls_wrap.js:628:8)
>     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38), stack=Error: Bad status [0]: Error: self signed certificate
>     at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
>     at emitNone (events.js:105:13)
>     at TLSSocket.emit (events.js:207:7)
>     at TLSSocket._finishInit (_tls_wrap.js:628:8)
>     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)
>     at exports.XMLHttpRequest.request.onreadystatechange (/opt/MineTime/resources/app.asar/node_modules/dav/dav.js:3719:25)
>     at exports.XMLHttpRequest.dispatchEvent (/opt/MineTime/resources/app.asar/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
>     at setState (/opt/MineTime/resources/app.asar/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
>     at exports.XMLHttpRequest.handleError (/opt/MineTime/resources/app.asar/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:532:5)
>     at ClientRequest.errorHandler (/opt/MineTime/resources/app.asar/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:459:14)
>     at emitOne (events.js:115:13)
>     at ClientRequest.emit (events.js:210:7)
>     at TLSSocket.socketErrorListener (_http_client.js:401:9)
>     at emitOne (events.js:115:13)
>     at TLSSocket.emit (events.js:210:7)
>     at emitErrorNT (internal/streams/destroy.js:64:8)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9), code=0

**Comment by marcoancona** [comment]
Beta support for self-signed certificate has been just released with 1.4.0. Feel free to comment in case of any issue.

**Comment by rauferd** [comment]
Adding a new account now works smoothly with servers using a self-signed SSL certificate.

However, I did not see any warning, confirmation dialog, or even information. This is less than ideal, since _most_ users would want to know about this situation and check the name and (ideally) fingerprint of the certificate (at least the first time they connect to a new server). Lacking a central signing authority, the user has to make sure he is connecting to the right server _himself_. This is currently not possible.

I didn't try, but this is another important question: is there be a BIG warning when the self signed (or any) certificate changes?

**Comment by marcoancona** [comment]
Are you still using NODE_TLS_REJECT_UNAUTHORIZED=0 ? 

This should not be necessary, and a warning should be showned upon first connection to a host with self-signed certificate instead.
If it is not what you experience, can you describe what happens when trying to connect to the host worth our the env variable set?

**Comment by rauferd** [comment]
I guess I did not fix that.

I can confirm that with MineTime 1.4.1 and without changing NODE_TLS_REJECT_UNAUTHORIZED, I do see the expected warning and can add an exception easily.

**Comment by rauferd** [comment]
However, MineTime did not display the name or fingerprint of the certificate (only ther server's domain name), making it kind of difficult to decide whether to confirm or abort

On the console I now see hundreds of messages popping up continuously:
> warn: Using TLS exception for ...
After the confirmation this should not be a warning anymore?

**Comment by lcguida** [comment]
I can't connect to a self signed server (local network via VPN) either. When using `NODE_TLS_REJECT_UNAUTHORIZED` it worked

**Comment by marcoancona** [comment]
When running without `NODE_TLS_REJECT_UNAUTHORIZED` and try to connect to the server, do you see a popup that asks to create an exception?

**Comment by lcguida** [comment]
No, I don't see any popup when connecting wihtout `NODE_TLS_REJECT_UNAUTHORIZED`.
