### ISSUE TITLE
Keep in Background should act like Close to Tray

### ISSUE THREAD

**Issue by nistath** [marcoancona/MineTime#61]
The Windows build of 1.3.2 has the option to keep the app running in the background, which is a necessity due to the startup time length. However the app remains in the taskbar even when the X/Close button is hit, acting the same way as minimizing the app. In certain task bar configurations (and in general) this is [annoying](https://i.kym-cdn.com/photos/images/original/000/632/529/e68.jpg).

![Taskbar](https://i.imgur.com/5Tr7fCw.png)

Following the example of Slack, you could allow the main window to close on hitting X/Alt+F4 and let the user restore it either by trying to launch the app again or by left-clicking on the tray icon in addition to the existing "Show MineTime" option.

**Comment by marcoancona** [comment]
New behavior in place in v.1.4.11. Feedbacks welcome.
