### ISSUE TITLE
Add "copy event" functionality (GUI & AI)

### ISSUE THREAD

**Issue by rauferd** [marcoancona/MineTime#65]
Even if they are not periodical events, many events are "much like" past events. They either share the same set of attendees, the same title, place & time, etc.

Therefore, it would be useful to add a "copy event" button to the event view (and maybe right click menu). Of course, the user will edit **some** parts of the new, copied event, otherwise it would be a duplicate (which should be automatically discarded).

The AI should understand this kind of logic as well:
"**Repeat** last week's uninon meeting next Friady"
"Schedule **another** business luncheon before the end of this month"
"Schuedule a dinner party **like in** July on 12.09."

**Comment by marcoancona** [comment]
Partially addressed in 1.5.0: it is now possible to duplicate (clone) events using Ctrl/Cmd+D or the right-click contextual menu. Due to the ambiguity of the query, it is more difficult to enable this operation on the AI assistant so at the moment we will not add this capability.
