### ISSUE TITLE
Whole day events displayed on the wrong day

### ISSUE THREAD

**Issue by flg** [marcoancona/MineTime#71]
As can be seen in the attached screenshot, a whole day event set for day X appears on day X-1 on the calendar view (week, month, day or agenda view).
![minetimewholeday](https://user-images.githubusercontent.com/325736/45218508-23d1c500-b2a8-11e8-8820-2dc5952a1b17.png)

**Comment by marcoancona** [comment]
Thanks for the notice. Is this a Google, Exchange, or CalDav calendar?

**Comment by flg** [comment]
This is for an Exchange calendar.
Trying to reproduce with the same Exchange calendar and with a Google calendar: I cannot reproduce it. But the (wrongly displayed) event from the original message is still in my calendar with still the same problem. I don't know what is specific about this. Let me know if and how I can provide more information.

**Comment by marcoancona** [comment]
This should be fixed in 1.4.5.
If the problem persists, please comment here so I can reopen this.

**Comment by flg** [comment]
Fix confirmed. Thank you.
