### ISSUE TITLE
support of using proxy

### ISSUE THREAD

**Issue by numb95** [marcoancona/MineTime#73]
Hey there. 
thanks for MineTime. it's awesome.
for me, I think it should be good to add support of proxy (HTTP, HTTPS, socks) to the MineTime. It would be helpful for Others.

thanks

**Comment by marcoancona** [comment]
For most calendar services, the correct proxy settings are inherited from the os. What calendar provider (Google, Exchange, Dav,...) are you using?

**Comment by numb95** [comment]
I use Google. because of my workplace network policies which restrict using some ports and protocols, i use several proxy servers for apps. because of that, I think it could be a good feature for MineTime.

**Comment by marcoancona** [comment]
Ok, then I'll close this as duplicate of #52 . We are just waiting for Google to fix their library to release this feature for Google calendar.
