### ISSUE TITLE
Add basic search capabilities

### ISSUE THREAD

**Issue by gwert** [marcoancona/MineTime#76]
It would be great to be able to search for meetings/appointments if you don't remember the date they're on.

**Comment by marcoancona** [comment]
In the roadmap already

**Comment by robot110011** [comment]
any update on the search feature?
btw many thanks for the app, I'm switching from mac to linux and your app is the best one!

**Comment by marcoancona** [comment]
Search capability now available in 1.5.0. Use Ctrl/Cmd+F or simply type `Find *your query*` in the assistant tab.
