### ISSUE TITLE
Support Google Advanced Protection Security Key 2FA

### ISSUE THREAD

**Issue by rcalixte** [marcoancona/MineTime#77]
For Google accounts configured with Advanced Protection (https://landing.google.com/advancedprotection/), the only way to provide the second factor of authentication on a desktop/laptop is via a Security Key (https://store.google.com/product/titan_security_key_kit).

As attached below, this functionality is not working and, at the moment, prevents any Google account with Advanced Protection from being able to be successfully added to the client.

![image](https://user-images.githubusercontent.com/10281587/46168987-e7bad000-c267-11e8-83d3-cf89d5aef87e.png)

**Comment by marcoancona** [comment]
Thanks for pointing out! This requires to change quite a bit in the authentication system. I added to our roadmap, but it might take a while.

**Comment by rcalixte** [comment]
@marcoancona Just an update on this:

Google has implemented a workaround for this as of December 19th for GSuite EAP customers. (A GSuite admin needs to enable this.) With the setting enabled, under the 'Try another way' dialogue, there is an option for a one-time security code that can be used to authorized the application in a user's account. This works for MineTime and should also work for any other applications with the same issue.

Thanks again!

**Comment by djmbritt** [comment]
Any updates on this feature?

**Comment by marcoancona** [comment]
We are about to release an update that redirects the user to his/her default browser for the authentication with Google, instead of using the internal browser that does not support Advanced Protection. However, it might be the case that the Calendar API are not accessible from this environment. 

Is any of you using another third-party calendar client connected to a Google account with Advanced Protection enabled?

**Comment by djmbritt** [comment]
That's great to hear, excited to try it out.
At the moment I'm not, no.
From what I've understood only a very limited number of apps support GAP at the moment.
Is there any other third party app that supports GAP?

**Comment by djmbritt** [comment]
It's working great for me :+1: 
Thanks!

**Comment by marcoancona** [comment]
Are you using version 1.5.0? Is the calendar syncing correctly?

**Comment by djmbritt** [comment]
Yes 1.5.0, I did have some issues that the names were not syncing properly. 
But from what I can tell everything else is syncing properly.
