### ISSUE TITLE
Feature request: add a keyboard shortcut to toggle dark theme

### ISSUE THREAD

**Issue by krupenja** [marcoancona/MineTime#78]
Would be great to have a keyboard shortcut to toggle dark theme. Alternatively, provide a command line switch to toggle between dark/light theme. My use case is using a custom shell script on Linux to toggle dark/light modes system-wide and having a keyboard shortcut could help as I can access it from script using `xdotool`.

**Comment by krupenja** [comment]
Tbh, I don't know: is twice a day frequent enough? :)

**Comment by marcoancona** [comment]
Definitely more than I would have imagined. We can add such a shortcut. What would you suggest?

**Comment by marcoancona** [comment]
Now available (Ctrl/Cmd+D) in 1.4.5
