### ISSUE TITLE
[Feature request] New events in a time zone

### ISSUE THREAD

**Issue by EmreAtes** [marcoancona/MineTime#82]
Could you add the option to add a new event in a specific time zone? For example if I get an email about a meeting at GMT-7 10am, can I select that instead of my local timezone when inputting the event?

Also, better multi-timezone support would be great, like seeing the calendar from a different timezone, scheduling meetings between people in different timezones, etc.

**Comment by marcoancona** [comment]
On the roadmap!

**Comment by marcoancona** [comment]
We have just released 1.4.6 and now you can set the timezone for new events as well as change it for existing ones. Notice that the chatbot assistant still does not recognize the timezone indication.
