### ISSUE TITLE
Full day event get assigned to two days

### ISSUE THREAD

**Issue by iagomosqueira** [marcoancona/MineTime#83]
When a full day event is created by clicking on the desired day in monthly view, it is saved by default as covering two days, the selected and the next one. I simply type the event name and then press Enter.

This is the view when editing

![edit](https://user-images.githubusercontent.com/1029847/46737658-5e11f600-cc9c-11e8-82fc-9e7cd5d18b70.png)

and this after saving

![save](https://user-images.githubusercontent.com/1029847/46737698-784bd400-cc9c-11e8-9b03-b318cc8286cb.png)

This is in v1.4.4, Ubuntu Linux 16.04, using CalDav to zoho.com

**Comment by marcoancona** [comment]
Fixed in 1.4.6

**Comment by iagomosqueira** [comment]
Great, many thanks.

**Comment by iagomosqueira** [comment]
This seems to be happening again in version 1.4.8. A single full day event

![1](https://user-images.githubusercontent.com/1029847/48770918-2eed9c00-ecc0-11e8-90e2-ee05d9229391.png)

gets assigned to two

![2](https://user-images.githubusercontent.com/1029847/48770938-38770400-ecc0-11e8-9f7d-d0cc335a767c.png)

And a two day event

![3](https://user-images.githubusercontent.com/1029847/48770951-42006c00-ecc0-11e8-81bf-7762503b72aa.png)

gets assigned three

![4](https://user-images.githubusercontent.com/1029847/48770964-49277a00-ecc0-11e8-93ba-38eb8ef5e043.png)

I am on MineTime 1.4.8, on a zoho.com Caldav calendar, on Ubuntu 18.04

**Comment by marcoancona** [comment]
What is the timezone MineTime is using? You can see this information on in the app settings tab.

**Comment by iagomosqueira** [comment]
It is GMT +02:00 Rome

**Comment by marcoancona** [comment]
We were able to reproduce the issue on a Zoho account. Please try the hot-fix in the latest release (1.4.9)

**Comment by iagomosqueira** [comment]
This seems to have fixed it, yes.
