### ISSUE TITLE
No sync with radicale since 1.4.4

### ISSUE THREAD

**Issue by freswa** [marcoancona/MineTime#84]
Since 1.4.4 my calendars on a radicale server (CalDAV account) do not sync anymore. Worked fine on 1.4.3, 1.4.1 and 1.4.0.
Are there any logs for debugging purposes?

**Comment by marcoancona** [comment]
You can try to type "analysis" on the assistant tab. This will open some logs. 
Can you try to relink the calendar?

**Comment by freswa** [comment]
Since the update the log is full of
```
2018-10-10T00:08:35.703Z - error: Error on sync of calendar 5b8de801004fcb3b0b53ca61. Next trial in in 30 secs... message=write EPROTO 110749696443200:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../../vendor/node/deps/openssl/openssl/ssl/s23_clnt.c:802:
, stack=Error: write EPROTO 110749696443200:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../../vendor/node/deps/openssl/openssl/ssl/s23_clnt.c:802:

    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14), code=EPROTO, errno=EPROTO, syscall=write, timestamp=2018-10-10T00:08:35.701Z

```
while I did not change anything on the server side.
Did you tweak something on the SSL settings?

I tried relinking which did not help and I eventually tried removing and readding the account while readding it does not work anymore with 1.4.4

**Comment by marcoancona** [comment]
Thanks a lot. We will look into this immediately! We upgraded some dependencies and it looks like there is a problem handling some SSL connections. I would suggest you downgrade to 1.4.3 while we look into a solution: https://github.com/marcoancona/MineTime/releases

**Comment by marcoancona** [comment]
Are you using any proxy?

**Comment by freswa** [comment]
I'm using nginx with this config (SSLv3 disabled):
```
ssl                         on;
ssl_prefer_server_ciphers   on;
ssl_protocols               TLSv1.2 TLSv1.3;
ssl_ciphers                 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
ssl_ecdh_curve              secp384r1;
```

**Comment by marcoancona** [comment]
https://github.com/nodejs/node/issues/16196

**Comment by marcoancona** [comment]
Do you have a way to provide us with a test account? Or would you be willing to try a patched version before we release it?

**Comment by freswa** [comment]
I can do both. You can contact me via email for details.

**Comment by freswa** [comment]
Published fix works. Thanks!
