### ISSUE TITLE
Multi-day event showing wrong date in calendar view

### ISSUE THREAD

**Issue by Pauligrinder** [marcoancona/MineTime#86]
I'm running MineTime 1.4.5 on Arch Linux (x86_64), and I have an event 27.-29.10, which shows in the calendar as 28.-30.10 (in all calendar views, Month/Week/Agenda/Day). The details-view shows the correct dates when I double click the event. 

The calendar is a Google Calendar and the event is set to start 15:15 on 27.10 and end at 11:40 on 29.10. I'm guessing this is related to #83 .

Please tell me if there's any way I can help debugging this! Here's a screenshot, with all unrelated events blurred out.

![minetime_bug](https://user-images.githubusercontent.com/5802137/47549814-e5e73980-d905-11e8-950a-e205a039d042.png)

**Comment by marcoancona** [comment]
Related to #83 . Will be fixed soon!

**Comment by marcoancona** [comment]
Fixed in 1.4.6

**Comment by Pauligrinder** [comment]
I just updated to 1.4.9 and can confirm that it's now fixed (the same event now shows on the right days). I missed the updates between though, I guess the update notification might be a little too non-intrusive (please keep it that way though).
