### ISSUE TITLE
run on Debian 32 bits?

### ISSUE THREAD

**Issue by Julien16** [marcoancona/MineTime#87]
Hi, is the AppImage supposed to work on debian i386 (Debian 9 testing branch)?
```
ju@debian:~/Downloads$ chmod +x MineTime-1.4.5-x86_64.AppImage
ju@debian:~/Downloads$ ./MineTime-1.4.5-x86_64.AppImage
bash: ./MineTime-1.4.5-x86_64.AppImage: cannot execute binary file: Exec format error
```
Any option to run your application on this machine? BTW, thanks for your work,

**Comment by marcoancona** [comment]
Hello,
No, I am afraid MineTime only works on 64bits architectures.

**Comment by Julien16** [comment]
Got it! Thanks
