### ISSUE TITLE
No notifications on Ubuntu 16.04.5 LTS

### ISSUE THREAD

**Issue by hemenkapadia** [marcoancona/MineTime#88]
Is there any known issue with MineTime and Ubuntu 16.04? I do not see any notifications popup for the meetings in my schedule.

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
```

**Comment by marcoancona** [comment]
Do you have `libnotify` installed? (but it should). Do you see the notification in you run `notify-send Test "Hello World"` from the terminal?

**Comment by hemenkapadia** [comment]
Yes. I do. Seems the notification is working. Closing this issue
