### ISSUE TITLE
Can't close minetime in arch linux [i3]

### ISSUE THREAD

**Issue by g4rrucho** [marcoancona/MineTime#91]
There's seems to be a problem with closing the application.
Using archlinux with i3, which kills the application with a shorcut defined by the user.
Only way to close app is with kill command or through the applet in the tray.

**Comment by marcoancona** [comment]
Is `Keep in background` enabled in the app settings? When this setting is enabled, the normal quit behavior is replaced with sort of "minimize to tray" behavior. The app becomes on purpose more difficult to close, but you should still be able to use the button from the tray or `CTRL+Q`.

**Comment by WingofaGriffin** [comment]
Using Cinnamon, `keep in background` keeps it both in the system tray, and in the active programs area. It would be nice to have it only stick in the tray when closed. The same is true of `CTRL+W` without it enabled.

**Comment by marcoancona** [comment]
We have just released an update that hides the task bar icon. Feedbacks on the new behavior are appreciated :)
