### ISSUE TITLE
MineTime asking for verification again

### ISSUE THREAD

**Issue by flg** [marcoancona/MineTime#92]
It may or mat not be related to this other ticket (that should be reopen): https://github.com/marcoancona/MineTime/issues/70

MineTime suddenly is showing the popup to verify the account again. It cannot be bypassed. Received the email, copy pasted the code, MineTime does not react, keeps showing: "Waiting for email verification..." Restarted MineTime just to test: it had lost the theme setting (dark) and is still waiting for the code apparently. There is no way to dismiss the original window asking to send email verification or the little window at the bottom for the "Waiting".

As I was mentionning in the other ticket: as this keeps happening, it would be nice to have a button to skip the calendar add/deletion step, and generally to be able to dismiss popups that are showing up, to by pass these issues.

**Comment by marcoancona** [comment]
Please upgrade to the lastest 1.4.6.

**Comment by flg** [comment]
Upgraded to 1.4.8. This version accepted the verification code. Thank you.
