### ISSUE TITLE
Notes and Comments to preserve white space

### ISSUE THREAD

**Issue by hemenkapadia** [marcoancona/MineTime#95]
On Ubuntu 16.04, Minetime version 1.4.9 I notice that any white spaces in the content is removed and everything gets condensed into one line.

Example: a Note like 
```
Agenda:  
1. Something
2. other thing 
```
gets converted to 

```
Agenda: 1. Something 2. other thing 
```

It would be great if the newline characters are preserved while creating the event.

**Comment by marcoancona** [comment]
Fixed in 1.5.1
