### ISSUE TITLE
can't connect to exchange server

### ISSUE THREAD

**Issue by cycomanic** [marcoancona/MineTime#96]
I'm getting an error when trying to connect to our university exchange server. I know I have the correct ews address and I can in fact connect to it in the browser (using username@domain, where domain is net in this case). I also can connect through other services (e.g. davmail there I put in net\username). However every posisble combination fails with minetime. Error log below:

```
error:  message=401 Unauthorized, InnerException=null, faultCode=null, faultString=null, faultActor=null, responseCode=127, errorCode=0, exceptionType=null, lineNumber=0, positionWithinLine=0, keys=[], , , keyPicker=function (value) { return value; }, HttpStatusCode=401, message=401 Unauthorized, InnerException=null
error: Exchange: failed to login message=Could not verify your credentials. Make sure your username, password and server adddress are correct. Your company might use a server address different from the default above. , stack=Error: Could not verify your credentials. Make sure your username, password and server adddress are correct. Your company might use a server address different from the default above.
```

**Comment by marcoancona** [comment]
Could you please email us your Exchange server URL at connect [at] minetime.ai 
It might be a problem with auto discover.

**Comment by cycomanic** [comment]
Hi,
the url is 
https://webmail.chalmers.se/ews/exchange.asmx

Regards
Jochen

**Comment by marcoancona** [comment]
I will close ad this issue is stalled. Feel free to comment if the problem persists.
