### ISSUE TITLE
timezone issues in caldav with davmail

### ISSUE THREAD

**Issue by cycomanic** [marcoancona/MineTime#97]
Because I can't use our exchange server I was trying davmail for accessing via caldav instead. However, when I try to create events in minetime I get a failure. I suspected this was an error in davmail, and reported it there (see https://sourceforge.net/p/davmail/bugs/693/)  Their dev's say this is an issue with minetime, which creates an invalid event:

> Got it: your event is invalid, it sends TZID:W. Europe Standard Time timezone and then uses TZID="Europe/Stockholm" in date values.
>VCALENDAR must contain time zone definitions matching TZIDs in VEVENTs

from the above bug report.

**Comment by marcoancona** [comment]
Now (v 1.4.11) MineTime adds the VTIMEZONE information. It would be helpful to know if this now works with davmail.

**Comment by cycomanic** [comment]
I can confirm minetime and davmail now work correctly together
