### ISSUE TITLE
Messed up UI 

### ISSUE THREAD

**Issue by arifzeeshan** [marcoancona/MineTime#99]
UI is messed up and I have text showing up instead of icon. This is what I mean. 

![screenshot_2018-12-24_04-10-39](https://user-images.githubusercontent.com/26674272/50388073-e8151b00-0731-11e9-8448-a8c11b12acc4.png)

In the top tight corner.

**Comment by marcoancona** [comment]
Does the problem persist now?

**Comment by arifzeeshan** [comment]
Yes, it persists.

**Comment by marcoancona** [comment]
Which version of macOS are you using?

**Comment by ducdigital** [comment]
It also happens on the latest version on KDE. Not sure why it missing all these icons.

![Screenshot_20190312_114539](https://user-images.githubusercontent.com/1712140/54194357-5d37f700-44bc-11e9-9acc-a60375116d7e.png)

**Comment by marcoancona** [comment]
Please check if this persists with the latest release 1.4.11

**Comment by marcoancona** [comment]
I assume this is now fixed. If the problem is encountered again, feel free to comment on this thread.
